{
  "hash": "82a39480214622967b04c5f6ce4b15d9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tesla Trend Analysis – Used Car Market 2024–2025\"\nauthor: \"Wasteson x TrackSights\"\nformat:\n  html:\n    theme: darkly\n    toc: true\n    toc-title: \"Table of Contents\"\n    number-sections: true\n    code-fold: true\n    code-tools: true\n    fig-cap-location: bottom\n    smooth-scroll: true\n    link-external-newwindow: true\neditor: visual\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n\n\n\n> ## 📋 Executive Summary\n>\n> **• Tesla diverged early.** While most EV brands followed a gradual growth curve, Tesla entered and exited its surge phase earlier – suggesting a sharper, brand-specific trajectory.\\\n> **• Price sensitivity varies.** Most segments showed textbook behavior: as listings increased, prices fell. Tesla, by contrast, remained price-stable – pointing to centralized pricing or brand insulation.\\\n> **• Timing overlaps with political signals.** The most significant structural shifts in volume occurred around the same time as Musk’s Trump endorsement – not proof of causation, but enough to warrant further scrutiny.\\\n> **• Tesla breaks the model.** Statistical models fit well for most segments, but Tesla’s higher residual error and flatter price–volume relationship point to episodic behavior and distinct market logic.\\\n> **• Implication: Watch Tesla.** Real-time monitoring of brand-specific shifts could provide a competitive edge – especially when sentiment and leadership cues drive market volatility.\n\n# 🎯 Objective\n\nExplore shifts in the Danish used car market during 2024–2025, with a focus on Tesla’s behavior in response to political signals – especially Elon Musk’s endorsement of Donald Trump.\n\nThe project uses a retrospective lens to illustrate how structural shifts can be surfaced early with the right data tooling. The key idea: timely insight is possible – but requires tracking and attention.\n\n# 🧪 Setup\n\nAll required packages are loaded in the processing chunk below. No special configurations were needed for this analysis. The document runs entirely within a local R environment using Quarto.\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n# 📘 Synopsis\n\nThis analysis explores structural shifts in the Danish used car market during 2024–2025, with a specific focus on Tesla's behavior relative to comparable brands. Our objective is twofold: to identify when significant changes in market volume occurred, and to assess whether Tesla responded differently to political signals – especially Elon Musk’s endorsement of Donald Trump.\n\nUsing weekly listing data from Bilbasen, we segmented the market by fuel type and brand, indexed volumes to a common baseline, and applied segmented regression to detect structural breakpoints in listing trends.\n\nTesla entered its surge phase slightly later (around week 23), but its second structural shift occurred earlier (week 36 vs. 38 for others). This indicates a faster transition through distinct growth phases – not a shorter growth period, but a more compressed and intense trajectory.\n\nWhile we cannot directly attribute Tesla’s movements to political events, the brand clearly diverged from peer behavior – both in timing and intensity. The temporal overlap with high-profile endorsements may be coincidental, or it may point to brand-specific sensitivity to external signals – such as consumer sentiment or leadership cues.\n\nPrice data reinforce this difference: most segments saw declining prices as supply grew, but Tesla remained remarkably price-stable – hinting at a different dynamic at play. This divergence opens the door for deeper questions: Is it brand loyalty? Centralized pricing? Political sentiment? The pattern is visible – the mechanism, less so.\n\nOverall, the analysis shows that structural changes were not only measurable – they were visible as they unfolded. Had this data been monitored in real time, a market actor could have:\\\n– Identified the emerging shift before it peaked\\\n– Reacted with smarter inventory or pricing moves\\\n– Asked sharper questions while competitors were still catching up\n\nIn a market as volatile and sentiment-driven as used EVs, timely insight is not a luxury – it’s an edge.\n\n------------------------------------------------------------------------\n\n# 🧪 Data Processing\n\nThis analysis is based on listing data from the Danish used car marketplace Bilbasen, extracted via TrackSights. The dataset spans from April 1, 2024, to March 14, 2025, and includes only retail listings.\n\nWe performed the following processing steps:\n\nDate parsing and filtering Listings were filtered to include only those with a valid RetailPrice and dates within the analysis window.\n\nFuel type classification Cars were grouped into two fuel groups based on FuelType: • Electric • Fossil (all non-electric drivetrains)\n\nSegment definition Based on brand and model, we created five analytical segments: Tesla (all models), VW ID (ID.3, ID.4, ID.5), Skoda Enyaq, electric vehicles, and fossil vehicles. In addition, a “Total market” segment was constructed for broader context.\n\nWeekly aggregation Listings were grouped by week using floor_date(), and smoothed using rolling averages where relevant.\n\nIndexing Volumes were normalized to an index (Week 1 = 100) per segment. This allows direct comparison of relative change over time.\n\nEvents overlay Key political events were added for context: • July 13, 2024 – Elon Musk publicly supports Donald Trump • November 5, 2024 – Trump wins the U.S. election • January 15, 2025 – Trump is inaugurated\n\n------------------------------------------------------------------------\n\n\n\n\n\n\n\n\n\n# 📊 Results\n\n## 📈 Market overview – Total vs Electric vs Fossil\n\nThe chart below shows the relative development in listing volume for fossil vehicles, electric vehicles, and the total used car market in Denmark – all indexed to April 2024 (week 1 = 100). A dramatic shift is visible from late summer 2024, with electric vehicles leading the surge.\n\n***Note on indexing**: The following charts use indexed volumes (Week 1 = 100) to show relative changes over time. This means we are comparing growth patterns – not absolute volumes. For example, Tesla may appear to outpace the EV market, but this reflects faster growth from a smaller base, not a larger total volume.*\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Indexed listing volume: Total vs Fossil vs Electric (Retail only, Index = 100 in April 2024)](index_files/figure-html/unnamed-chunk-4-1.png){width=864}\n:::\n:::\n\n\n\n\n## 🔍 Brand comparison – Tesla vs VW ID\n\nDirect volume comparison between two comparable brands. Tesla displays more volatility and sharper surges, suggesting a faster transition once growth begins.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![📈 Indexed listing volume: Tesla vs VW ID (Retail only, Index = 100 in April 2024)](index_files/figure-html/volume_tesla_vw-1.png){width=864}\n:::\n:::\n\n\n\n\n## 📐 Structural breakpoints – Segmented regression\n\nWhen did volume behavior change?\\\nWe compare Tesla, VW ID, Skoda Enyaq, the total market, and broader EVs using segmented regression.\\\nBoth one- and two-breakpoint models were tested to assess structural shifts in listing volumes.\n\n**Findings**\\\nThe one-breakpoint model suggested that Tesla shifted earlier than the rest – with a change around week 30, while other segments (VW ID, Enyaq, EVs, total market) shifted later, typically in week 38.\n\nTo test this further, we applied a two-breakpoint model to explore potential phase transitions:\n\n-   Tesla entered its growth phase slightly after others (week 23)\\\n-   But its second structural shift occurred earlier (week 36 vs. week 38 for peers)\n\n**Interpretation**\\\nTesla’s volume curve was more compressed and sharper, suggesting a distinct growth pattern:\\\n⚡ Not out of sync – but different. This supports the idea of brand-specific drivers, rather than a uniform EV market trend.\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Segmented regression (2 breakpoints): Tesla, VW ID, Electric vehicles\n\n|Segment           |Breakpoints |   R²| Residual Std. Error|\n|:-----------------|:-----------|----:|-------------------:|\n|Tesla             |23, 36      | 0.90|             1700.16|\n|VW ID             |21, 38      | 0.93|              887.77|\n|Electric vehicles |21.3, 38    | 0.95|             1187.67|\n\n\n:::\n:::\n\n\n\n\nModel interpretation: Tesla vs. peers\n\nWhile all models exhibit a good fit (R² \\> 0.90), there are notable differences in residual error.\n\nTesla shows the **lowest R² (0.90)** and **highest residual standard error (1700)** compared to VW ID (R² = 0.93, RSE ≈ 888) and the broader EV segment (R² = 0.95, RSE ≈ 1188).\n\nThis suggests that Tesla’s volume curve is **less well captured by a simple two-phase model**, and likely reflects:\n\n-   **Sharper transitions** in listing behavior (e.g., price cuts, sudden demand surges)\n-   **More episodic dynamics**, potentially driven by brand-specific strategies\n-   **Outlier events** or volatility not present in other EV segments\n\n🧠 *Interpretation:*\\\nThe higher residual variation reinforces the idea that Tesla’s structural shifts follow a **more distinct and compressed pattern**, which supports the argument for **brand-specific timing mechanisms** rather than a uniform EV market trend.\n\n## Timing of breakpoints in listing trends\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Timing of structural shifts in listing volume – segmented regression breakpoints (2 per brand)](index_files/figure-html/breakpoint_plot-1.png){width=864}\n:::\n:::\n\n\n\n\n\"Breakpoints show a more compressed transition for Tesla: it entered its growth phase slightly later, but exhibited an earlier structural shift in pattern. Peers (VW ID, EV market) followed a broader, more aligned trajectory across the period.\"\n\n# 💸 Price dynamics\n\nHow did prices respond to the volume shift?\n\nThis section investigates whether listing volumes and median retail prices moved in tandem – or diverged – across segments.\n\nWe apply three main analytical lenses in the main section:\n\n1.  **Correlation analysis** – do higher volumes coincide with lower prices?\\\n2.  **Price–volume scatterplots** – visualizing the relationship\\\n3.  **LOESS smoothing** – uncovering broader structural price trends\n\n📎 *Supplementary figures are available in the Appendix.*\n\n------------------------------------------------------------------------\n\n\n\n\n\n\n\n\n\n## 📊 Correlation: Price vs. Volume\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Correlation between weekly listing volume and median retail price\n\n|Segment           | Pearson correlation| P-value|\n|:-----------------|-------------------:|-------:|\n|Tesla             |              -0.085|   0.595|\n|VW ID             |              -0.420|   0.002|\n|Electric vehicles |              -0.649|   0.000|\n|Fossil vehicles   |              -0.670|   0.000|\n\n\n:::\n:::\n\n\n\n\n**Interpretation**\n\n-   📉 **Fossil vehicles and EVs**: strong negative correlation → more listings = lower prices\\\n-   📉 **VW ID**: moderate but significant correlation\\\n-   ➖ **Tesla**: nearly flat, non-significant relationship (r = –0.085, p = 0.595)\n\nThis suggests that **Tesla’s prices were less sensitive to changes in listing volume**, diverging from other segments.\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n## 🔁 Scatterplot – Volume vs median price for selected brands\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Volume vs. median retail price – Selected brands (Tesla, VW ID, Skoda Enyaq)](index_files/figure-html/price_volume_selected_brands-1.png){width=864}\n:::\n:::\n\n\n\n\n**Interpretation**\\\n\nThis scatterplot shows the relationship between **weekly listing volume** (x-axis) and **median retail price** (y-axis) for three EV brands: **Tesla**, **VW ID**, and **Skoda Enyaq**. Each point represents one week; the trendlines show the direction and strength of that relationship for each brand. Two visual elements are key here:\n\n**Slope of the line** → how prices respond to changes in volume\\\n\n– A **steeper negative slope** means prices drop as listings rise (more price-sensitive).\\\n\n– A **flat line** indicates prices remain stable regardless of supply.\n\n**Length of the line** → the range of observed volumes\\\n\n– A **longer line** means that the segment has been listed across a wider range of weekly volumes.\\\n\n– A **shorter line** signals that the brand rarely reaches high volumes – so price behavior is only observed within a narrower supply band.\n\n**Findings**\\\n\n– **VW ID** combines a long line and a steep slope – indicating both high listing activity and strong price sensitivity.\\\n\n– **Skoda Enyaq** has a shorter but steep line – fewer weeks with high volume, but still a clear price drop pattern.\\\n\n– **Tesla** displays a flat and relatively short line – suggesting stable prices across a narrow volume range, reinforcing earlier signs of centralized pricing or limited responsiveness to weekly market conditions.\n\nTogether, these patterns reveal that **volume alone doesn't determine pricing power** – the brand matters, and Tesla continues to diverge from peers in how it responds to market shifts.\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n## 📐 Smoothed Price Trends (LOESS)\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![LOESS-smoothed price trends per segment](index_files/figure-html/loess_price_trend-1.png){width=864}\n:::\n:::\n\n\n\n\n**Interpretation**\\\nThis chart shows smoothed weekly median prices using LOESS – a local regression technique that highlights broad trends while filtering out week-to-week noise.\n\n-   **Fossil vehicles** display a steady decline, suggesting sustained price pressure across the period.\\\n-   **Electric vehicles** show more fluctuation but a generally downward trend, indicating both volatility and emerging price normalization.\\\n-   **VW ID** closely tracks the broader EV market, reinforcing its role as a representative subsegment.\\\n-   **Tesla** stands out with elevated and relatively stable prices – despite some variation, the curve suggests resilience compared to peers.\n\nIn essence, this view highlights **the structural separation in pricing levels** between segments – with Tesla maintaining premium positioning.\n\n------------------------------------------------------------------------\n\n## 🧠 **Final takeaway**\n\nWhile most segments followed textbook supply–demand logic (volume up → price down), Tesla defied the trend. Its prices remained elevated and stable, even as listings grew – signaling brand-specific dynamics, insulation, or deliberate pricing control.\n\nTesla doesn’t just behave differently – it moves on its own terms.\n\n**In short, the pattern is visible – and we’ve surfaced the shift.**\n\n------------------------------------------------------------------------\n\n# 📎 Appendix\n\n## Weekly median retail prices\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Weekly median retail prices – Total market, Fossil, and EV segments](index_files/figure-html/price_median_all-1.png){width=864}\n:::\n:::\n\n\n\n\nFossil vehicles held stable throughout the period, with only gradual decline – a hallmark of a mature, supply-stable segment. EV prices, by contrast, started high and trended downward. This supports the idea of market normalization: more listings, more competition, and an erosion of the early EV price premium.\n\n## Weekly median retail prices - Tesla vs VW ID\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Weekly median prices – Tesla vs VW ID](index_files/figure-html/price_median_tesla_vw-1.png){width=864}\n:::\n:::\n\n\n\n\nDespite similar volumes, price dynamics diverge sharply. VW ID follows a modest and stable path. Tesla, meanwhile, swings unpredictably – suggesting sensitivity to external cues or internal recalibration. Volatility here may not signal chaos, but control: pricing used as an active lever.\n\n## 📏 Indexed Prices (Week 1 = 100)\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Retail price index per segment (Week 1 = 100)](index_files/figure-html/price_index_plot-1.png){width=864}\n:::\n:::\n\n\n\n\nIndexing reveals a clearer narrative: Fossil and EV prices decline together, but Tesla defies the trend. Its price index remains elevated – fluctuating, but consistently above peers. This reinforces earlier points: Tesla isn't just another EV brand, it moves to its own logic – structurally distinct in both volume and price.\n\n## Total markets volume vs. Price – Scatter\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Scatterplot – Weekly volume vs median price (per segment)](index_files/figure-html/price_volume_scatter-1.png){width=864}\n:::\n:::\n\n\n\n\nThis scatterplot quantifies what we’ve hinted at: volume correlates negatively with price across segments – except for Tesla. Where others follow the textbook rule (more listings = lower prices), Tesla’s line is nearly flat. It absorbs volume without discounting – or at least, without obvious market-based pressure.\n\nTogether, these charts reinforce the central pattern: Tesla doesn’t just behave differently – it prices differently, moves differently, and responds to change on its own terms. For market watchers, that makes it both harder to predict – and more important to watch.\n\n\\\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}