<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Wasteson x TrackSights">

<title>Tesla Trend Analysis – Used Car Market 2024–2025 – Tesla Market Shift</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Tesla Market Shift</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of Contents</h2>
   
  <ul>
  <li><a href="#objective" id="toc-objective" class="nav-link active" data-scroll-target="#objective"><span class="header-section-number">1</span> 🎯 Objective</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">2</span> 🧪 Setup</a></li>
  <li><a href="#synopsis" id="toc-synopsis" class="nav-link" data-scroll-target="#synopsis"><span class="header-section-number">3</span> 📘 Synopsis</a></li>
  <li><a href="#data-processing" id="toc-data-processing" class="nav-link" data-scroll-target="#data-processing"><span class="header-section-number">4</span> 🧪 Data Processing</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">5</span> 📊 Results</a>
  <ul class="collapse">
  <li><a href="#market-overview-total-vs-electric-vs-fossil" id="toc-market-overview-total-vs-electric-vs-fossil" class="nav-link" data-scroll-target="#market-overview-total-vs-electric-vs-fossil"><span class="header-section-number">5.1</span> 📈 Market overview – Total vs Electric vs Fossil</a></li>
  <li><a href="#brand-comparison-tesla-vs-vw-id" id="toc-brand-comparison-tesla-vs-vw-id" class="nav-link" data-scroll-target="#brand-comparison-tesla-vs-vw-id"><span class="header-section-number">5.2</span> 🔍 Brand comparison – Tesla vs VW ID</a></li>
  <li><a href="#structural-breakpoints-segmented-regression" id="toc-structural-breakpoints-segmented-regression" class="nav-link" data-scroll-target="#structural-breakpoints-segmented-regression"><span class="header-section-number">5.3</span> 📐 Structural breakpoints – Segmented regression</a></li>
  <li><a href="#timing-of-breakpoints-in-listing-trends" id="toc-timing-of-breakpoints-in-listing-trends" class="nav-link" data-scroll-target="#timing-of-breakpoints-in-listing-trends"><span class="header-section-number">5.4</span> Timing of breakpoints in listing trends</a></li>
  </ul></li>
  <li><a href="#price-dynamics" id="toc-price-dynamics" class="nav-link" data-scroll-target="#price-dynamics"><span class="header-section-number">6</span> 💸 Price dynamics</a>
  <ul class="collapse">
  <li><a href="#correlation-price-vs.-volume" id="toc-correlation-price-vs.-volume" class="nav-link" data-scroll-target="#correlation-price-vs.-volume"><span class="header-section-number">6.1</span> 📊 Correlation: Price vs.&nbsp;Volume</a></li>
  <li><a href="#scatterplot-volume-vs-median-price-for-selected-brands" id="toc-scatterplot-volume-vs-median-price-for-selected-brands" class="nav-link" data-scroll-target="#scatterplot-volume-vs-median-price-for-selected-brands"><span class="header-section-number">6.2</span> 🔁 Scatterplot – Volume vs median price for selected brands</a></li>
  <li><a href="#smoothed-price-trends-loess" id="toc-smoothed-price-trends-loess" class="nav-link" data-scroll-target="#smoothed-price-trends-loess"><span class="header-section-number">6.3</span> 📐 Smoothed Price Trends (LOESS)</a></li>
  <li><a href="#final-takeaway" id="toc-final-takeaway" class="nav-link" data-scroll-target="#final-takeaway"><span class="header-section-number">6.4</span> 🧠 <strong>Final takeaway</strong></a></li>
  </ul></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix"><span class="header-section-number">7</span> 📎 Appendix</a>
  <ul class="collapse">
  <li><a href="#weekly-median-retail-prices" id="toc-weekly-median-retail-prices" class="nav-link" data-scroll-target="#weekly-median-retail-prices"><span class="header-section-number">7.1</span> Weekly median retail prices</a></li>
  <li><a href="#weekly-median-retail-prices---tesla-vs-vw-id" id="toc-weekly-median-retail-prices---tesla-vs-vw-id" class="nav-link" data-scroll-target="#weekly-median-retail-prices---tesla-vs-vw-id"><span class="header-section-number">7.2</span> Weekly median retail prices - Tesla vs VW ID</a></li>
  <li><a href="#indexed-prices-week-1-100" id="toc-indexed-prices-week-1-100" class="nav-link" data-scroll-target="#indexed-prices-week-1-100"><span class="header-section-number">7.3</span> 📏 Indexed Prices (Week 1 = 100)</a></li>
  <li><a href="#total-markets-volume-vs.-price-scatter" id="toc-total-markets-volume-vs.-price-scatter" class="nav-link" data-scroll-target="#total-markets-volume-vs.-price-scatter"><span class="header-section-number">7.4</span> Total markets volume vs.&nbsp;Price – Scatter</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Tesla Trend Analysis – Used Car Market 2024–2025</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Wasteson x TrackSights </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<h2 id="executive-summary" data-number="0.1" class="anchored"><span class="header-section-number">0.1</span> 📋 Executive Summary</h2>
<p><strong>• Tesla diverged early.</strong> While most EV brands followed a gradual growth curve, Tesla entered and exited its surge phase earlier – suggesting a sharper, brand-specific trajectory.<br>
<strong>• Price sensitivity varies.</strong> Most segments showed textbook behavior: as listings increased, prices fell. Tesla, by contrast, remained price-stable – pointing to centralized pricing or brand insulation.<br>
<strong>• Timing overlaps with political signals.</strong> The most significant structural shifts in volume occurred around the same time as Musk’s Trump endorsement – not proof of causation, but enough to warrant further scrutiny.<br>
<strong>• Tesla breaks the model.</strong> Statistical models fit well for most segments, but Tesla’s higher residual error and flatter price–volume relationship point to episodic behavior and distinct market logic.<br>
<strong>• Implication: Watch Tesla.</strong> Real-time monitoring of brand-specific shifts could provide a competitive edge – especially when sentiment and leadership cues drive market volatility.</p>
</blockquote>
<section id="objective" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> 🎯 Objective</h1>
<p>Explore shifts in the Danish used car market during 2024–2025, with a focus on Tesla’s behavior in response to political signals – especially Elon Musk’s endorsement of Donald Trump.</p>
<p>The project uses a retrospective lens to illustrate how structural shifts can be surfaced early with the right data tooling. The key idea: timely insight is possible – but requires tracking and attention.</p>
</section>
<section id="setup" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> 🧪 Setup</h1>
<p>All required packages are loaded in the processing chunk below. No special configurations were needed for this analysis. The document runs entirely within a local R environment using Quarto.</p>
</section>
<section id="synopsis" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> 📘 Synopsis</h1>
<p>This analysis explores structural shifts in the Danish used car market during 2024–2025, with a specific focus on Tesla’s behavior relative to comparable brands. Our objective is twofold: to identify when significant changes in market volume occurred, and to assess whether Tesla responded differently to political signals – especially Elon Musk’s endorsement of Donald Trump.</p>
<p>Using weekly listing data from Bilbasen, we segmented the market by fuel type and brand, indexed volumes to a common baseline, and applied segmented regression to detect structural breakpoints in listing trends.</p>
<p>Tesla entered its surge phase slightly later (around week 23), but its second structural shift occurred earlier (week 36 vs.&nbsp;38 for others). This indicates a faster transition through distinct growth phases – not a shorter growth period, but a more compressed and intense trajectory.</p>
<p>While we cannot directly attribute Tesla’s movements to political events, the brand clearly diverged from peer behavior – both in timing and intensity. The temporal overlap with high-profile endorsements may be coincidental, or it may point to brand-specific sensitivity to external signals – such as consumer sentiment or leadership cues.</p>
<p>Price data reinforce this difference: most segments saw declining prices as supply grew, but Tesla remained remarkably price-stable – hinting at a different dynamic at play. This divergence opens the door for deeper questions: Is it brand loyalty? Centralized pricing? Political sentiment? The pattern is visible – the mechanism, less so.</p>
<p>Overall, the analysis shows that structural changes were not only measurable – they were visible as they unfolded. Had this data been monitored in real time, a market actor could have:<br>
– Identified the emerging shift before it peaked<br>
– Reacted with smarter inventory or pricing moves<br>
– Asked sharper questions while competitors were still catching up</p>
<p>In a market as volatile and sentiment-driven as used EVs, timely insight is not a luxury – it’s an edge.</p>
<hr>
</section>
<section id="data-processing" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> 🧪 Data Processing</h1>
<p>This analysis is based on listing data from the Danish used car marketplace Bilbasen, extracted via TrackSights. The dataset spans from April 1, 2024, to March 14, 2025, and includes only retail listings.</p>
<p>We performed the following processing steps:</p>
<p>Date parsing and filtering Listings were filtered to include only those with a valid RetailPrice and dates within the analysis window.</p>
<p>Fuel type classification Cars were grouped into two fuel groups based on FuelType: • Electric • Fossil (all non-electric drivetrains)</p>
<p>Segment definition Based on brand and model, we created five analytical segments: Tesla (all models), VW ID (ID.3, ID.4, ID.5), Skoda Enyaq, electric vehicles, and fossil vehicles. In addition, a “Total market” segment was constructed for broader context.</p>
<p>Weekly aggregation Listings were grouped by week using floor_date(), and smoothed using rolling averages where relevant.</p>
<p>Indexing Volumes were normalized to an index (Week 1 = 100) per segment. This allows direct comparison of relative change over time.</p>
<p>Events overlay Key political events were added for context: • July 13, 2024 – Elon Musk publicly supports Donald Trump • November 5, 2024 – Trump wins the U.S. election • January 15, 2025 – Trump is inaugurated</p>
<hr>
</section>
<section id="results" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> 📊 Results</h1>
<section id="market-overview-total-vs-electric-vs-fossil" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="market-overview-total-vs-electric-vs-fossil"><span class="header-section-number">5.1</span> 📈 Market overview – Total vs Electric vs Fossil</h2>
<p>The chart below shows the relative development in listing volume for fossil vehicles, electric vehicles, and the total used car market in Denmark – all indexed to April 2024 (week 1 = 100). A dramatic shift is visible from late summer 2024, with electric vehicles leading the surge.</p>
<p><em><strong>Note on indexing</strong>: The following charts use indexed volumes (Week 1 = 100) to show relative changes over time. This means we are comparing growth patterns – not absolute volumes. For example, Tesla may appear to outpace the EV market, but this reflects faster growth from a smaller base, not a larger total volume.</em></p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Indexed listing volume: Total vs Fossil vs Electric (Retail only, Index = 100 in April 2024)</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="brand-comparison-tesla-vs-vw-id" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="brand-comparison-tesla-vs-vw-id"><span class="header-section-number">5.2</span> 🔍 Brand comparison – Tesla vs VW ID</h2>
<p>Direct volume comparison between two comparable brands. Tesla displays more volatility and sharper surges, suggesting a faster transition once growth begins.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/volume_tesla_vw-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>📈 Indexed listing volume: Tesla vs VW ID (Retail only, Index = 100 in April 2024)</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="structural-breakpoints-segmented-regression" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="structural-breakpoints-segmented-regression"><span class="header-section-number">5.3</span> 📐 Structural breakpoints – Segmented regression</h2>
<p>When did volume behavior change?<br>
We compare Tesla, VW ID, Skoda Enyaq, the total market, and broader EVs using segmented regression.<br>
Both one- and two-breakpoint models were tested to assess structural shifts in listing volumes.</p>
<p><strong>Findings</strong><br>
The one-breakpoint model suggested that Tesla shifted earlier than the rest – with a change around week 30, while other segments (VW ID, Enyaq, EVs, total market) shifted later, typically in week 38.</p>
<p>To test this further, we applied a two-breakpoint model to explore potential phase transitions:</p>
<ul>
<li>Tesla entered its growth phase slightly after others (week 23)<br>
</li>
<li>But its second structural shift occurred earlier (week 36 vs.&nbsp;week 38 for peers)</li>
</ul>
<p><strong>Interpretation</strong><br>
Tesla’s volume curve was more compressed and sharper, suggesting a distinct growth pattern:<br>
⚡ Not out of sync – but different. This supports the idea of brand-specific drivers, rather than a uniform EV market trend.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Segmented regression (2 breakpoints): Tesla, VW ID, Electric vehicles</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Segment</th>
<th style="text-align: left;">Breakpoints</th>
<th style="text-align: right;">R²</th>
<th style="text-align: right;">Residual Std. Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Tesla</td>
<td style="text-align: left;">23, 36</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">1700.16</td>
</tr>
<tr class="even">
<td style="text-align: left;">VW ID</td>
<td style="text-align: left;">21, 38</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">887.77</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Electric vehicles</td>
<td style="text-align: left;">21.3, 38</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">1187.67</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Model interpretation: Tesla vs.&nbsp;peers</p>
<p>While all models exhibit a good fit (R² &gt; 0.90), there are notable differences in residual error.</p>
<p>Tesla shows the <strong>lowest R² (0.90)</strong> and <strong>highest residual standard error (1700)</strong> compared to VW ID (R² = 0.93, RSE ≈ 888) and the broader EV segment (R² = 0.95, RSE ≈ 1188).</p>
<p>This suggests that Tesla’s volume curve is <strong>less well captured by a simple two-phase model</strong>, and likely reflects:</p>
<ul>
<li><strong>Sharper transitions</strong> in listing behavior (e.g., price cuts, sudden demand surges)</li>
<li><strong>More episodic dynamics</strong>, potentially driven by brand-specific strategies</li>
<li><strong>Outlier events</strong> or volatility not present in other EV segments</li>
</ul>
<p>🧠 <em>Interpretation:</em><br>
The higher residual variation reinforces the idea that Tesla’s structural shifts follow a <strong>more distinct and compressed pattern</strong>, which supports the argument for <strong>brand-specific timing mechanisms</strong> rather than a uniform EV market trend.</p>
</section>
<section id="timing-of-breakpoints-in-listing-trends" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="timing-of-breakpoints-in-listing-trends"><span class="header-section-number">5.4</span> Timing of breakpoints in listing trends</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/breakpoint_plot-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Timing of structural shifts in listing volume – segmented regression breakpoints (2 per brand)</figcaption>
</figure>
</div>
</div>
</div>
<p>“Breakpoints show a more compressed transition for Tesla: it entered its growth phase slightly later, but exhibited an earlier structural shift in pattern. Peers (VW ID, EV market) followed a broader, more aligned trajectory across the period.”</p>
</section>
</section>
<section id="price-dynamics" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> 💸 Price dynamics</h1>
<p>How did prices respond to the volume shift?</p>
<p>This section investigates whether listing volumes and median retail prices moved in tandem – or diverged – across segments.</p>
<p>We apply three main analytical lenses in the main section:</p>
<ol type="1">
<li><strong>Correlation analysis</strong> – do higher volumes coincide with lower prices?<br>
</li>
<li><strong>Price–volume scatterplots</strong> – visualizing the relationship<br>
</li>
<li><strong>LOESS smoothing</strong> – uncovering broader structural price trends</li>
</ol>
<p>📎 <em>Supplementary figures are available in the Appendix.</em></p>
<hr>
<section id="correlation-price-vs.-volume" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="correlation-price-vs.-volume"><span class="header-section-number">6.1</span> 📊 Correlation: Price vs.&nbsp;Volume</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Correlation between weekly listing volume and median retail price</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Segment</th>
<th style="text-align: right;">Pearson correlation</th>
<th style="text-align: right;">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Tesla</td>
<td style="text-align: right;">-0.085</td>
<td style="text-align: right;">0.595</td>
</tr>
<tr class="even">
<td style="text-align: left;">VW ID</td>
<td style="text-align: right;">-0.420</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Electric vehicles</td>
<td style="text-align: right;">-0.649</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fossil vehicles</td>
<td style="text-align: right;">-0.670</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li>📉 <strong>Fossil vehicles and EVs</strong>: strong negative correlation → more listings = lower prices<br>
</li>
<li>📉 <strong>VW ID</strong>: moderate but significant correlation<br>
</li>
<li>➖ <strong>Tesla</strong>: nearly flat, non-significant relationship (r = –0.085, p = 0.595)</li>
</ul>
<p>This suggests that <strong>Tesla’s prices were less sensitive to changes in listing volume</strong>, diverging from other segments.</p>
<hr>
<hr>
</section>
<section id="scatterplot-volume-vs-median-price-for-selected-brands" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="scatterplot-volume-vs-median-price-for-selected-brands"><span class="header-section-number">6.2</span> 🔁 Scatterplot – Volume vs median price for selected brands</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/price_volume_selected_brands-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Volume vs.&nbsp;median retail price – Selected brands (Tesla, VW ID, Skoda Enyaq)</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong><br>
</p>
<p>This scatterplot shows the relationship between <strong>weekly listing volume</strong> (x-axis) and <strong>median retail price</strong> (y-axis) for three EV brands: <strong>Tesla</strong>, <strong>VW ID</strong>, and <strong>Skoda Enyaq</strong>. Each point represents one week; the trendlines show the direction and strength of that relationship for each brand. Two visual elements are key here:</p>
<p><strong>Slope of the line</strong> → how prices respond to changes in volume<br>
</p>
<p>– A <strong>steeper negative slope</strong> means prices drop as listings rise (more price-sensitive).<br>
</p>
<p>– A <strong>flat line</strong> indicates prices remain stable regardless of supply.</p>
<p><strong>Length of the line</strong> → the range of observed volumes<br>
</p>
<p>– A <strong>longer line</strong> means that the segment has been listed across a wider range of weekly volumes.<br>
</p>
<p>– A <strong>shorter line</strong> signals that the brand rarely reaches high volumes – so price behavior is only observed within a narrower supply band.</p>
<p><strong>Findings</strong><br>
</p>
<p>– <strong>VW ID</strong> combines a long line and a steep slope – indicating both high listing activity and strong price sensitivity.<br>
</p>
<p>– <strong>Skoda Enyaq</strong> has a shorter but steep line – fewer weeks with high volume, but still a clear price drop pattern.<br>
</p>
<p>– <strong>Tesla</strong> displays a flat and relatively short line – suggesting stable prices across a narrow volume range, reinforcing earlier signs of centralized pricing or limited responsiveness to weekly market conditions.</p>
<p>Together, these patterns reveal that <strong>volume alone doesn’t determine pricing power</strong> – the brand matters, and Tesla continues to diverge from peers in how it responds to market shifts.</p>
<hr>
<hr>
</section>
<section id="smoothed-price-trends-loess" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="smoothed-price-trends-loess"><span class="header-section-number">6.3</span> 📐 Smoothed Price Trends (LOESS)</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/loess_price_trend-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>LOESS-smoothed price trends per segment</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong><br>
This chart shows smoothed weekly median prices using LOESS – a local regression technique that highlights broad trends while filtering out week-to-week noise.</p>
<ul>
<li><strong>Fossil vehicles</strong> display a steady decline, suggesting sustained price pressure across the period.<br>
</li>
<li><strong>Electric vehicles</strong> show more fluctuation but a generally downward trend, indicating both volatility and emerging price normalization.<br>
</li>
<li><strong>VW ID</strong> closely tracks the broader EV market, reinforcing its role as a representative subsegment.<br>
</li>
<li><strong>Tesla</strong> stands out with elevated and relatively stable prices – despite some variation, the curve suggests resilience compared to peers.</li>
</ul>
<p>In essence, this view highlights <strong>the structural separation in pricing levels</strong> between segments – with Tesla maintaining premium positioning.</p>
<hr>
</section>
<section id="final-takeaway" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="final-takeaway"><span class="header-section-number">6.4</span> 🧠 <strong>Final takeaway</strong></h2>
<p>While most segments followed textbook supply–demand logic (volume up → price down), Tesla defied the trend. Its prices remained elevated and stable, even as listings grew – signaling brand-specific dynamics, insulation, or deliberate pricing control.</p>
<p>Tesla doesn’t just behave differently – it moves on its own terms.</p>
<p><strong>In short, the pattern is visible – and we’ve surfaced the shift.</strong></p>
<hr>
</section>
</section>
<section id="appendix" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> 📎 Appendix</h1>
<section id="weekly-median-retail-prices" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="weekly-median-retail-prices"><span class="header-section-number">7.1</span> Weekly median retail prices</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/price_median_all-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Weekly median retail prices – Total market, Fossil, and EV segments</figcaption>
</figure>
</div>
</div>
</div>
<p>Fossil vehicles held stable throughout the period, with only gradual decline – a hallmark of a mature, supply-stable segment. EV prices, by contrast, started high and trended downward. This supports the idea of market normalization: more listings, more competition, and an erosion of the early EV price premium.</p>
</section>
<section id="weekly-median-retail-prices---tesla-vs-vw-id" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="weekly-median-retail-prices---tesla-vs-vw-id"><span class="header-section-number">7.2</span> Weekly median retail prices - Tesla vs VW ID</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/price_median_tesla_vw-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Weekly median prices – Tesla vs VW ID</figcaption>
</figure>
</div>
</div>
</div>
<p>Despite similar volumes, price dynamics diverge sharply. VW ID follows a modest and stable path. Tesla, meanwhile, swings unpredictably – suggesting sensitivity to external cues or internal recalibration. Volatility here may not signal chaos, but control: pricing used as an active lever.</p>
</section>
<section id="indexed-prices-week-1-100" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="indexed-prices-week-1-100"><span class="header-section-number">7.3</span> 📏 Indexed Prices (Week 1 = 100)</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/price_index_plot-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Retail price index per segment (Week 1 = 100)</figcaption>
</figure>
</div>
</div>
</div>
<p>Indexing reveals a clearer narrative: Fossil and EV prices decline together, but Tesla defies the trend. Its price index remains elevated – fluctuating, but consistently above peers. This reinforces earlier points: Tesla isn’t just another EV brand, it moves to its own logic – structurally distinct in both volume and price.</p>
</section>
<section id="total-markets-volume-vs.-price-scatter" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="total-markets-volume-vs.-price-scatter"><span class="header-section-number">7.4</span> Total markets volume vs.&nbsp;Price – Scatter</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/price_volume_scatter-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Scatterplot – Weekly volume vs median price (per segment)</figcaption>
</figure>
</div>
</div>
</div>
<p>This scatterplot quantifies what we’ve hinted at: volume correlates negatively with price across segments – except for Tesla. Where others follow the textbook rule (more listings = lower prices), Tesla’s line is nearly flat. It absorbs volume without discounting – or at least, without obvious market-based pressure.</p>
<p>Together, these charts reinforce the central pattern: Tesla doesn’t just behave differently – it prices differently, moves differently, and responds to change on its own terms. For market watchers, that makes it both harder to predict – and more important to watch.</p>
<p><br>
</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Tesla Trend Analysis – Used Car Market 2024–2025"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Wasteson x TrackSights"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: darkly</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-title: "Table of Contents"</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-cap-location: bottom</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">    smooth-scroll: true</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">    link-external-newwindow: true</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="an">editor:</span><span class="co"> visual</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: false</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; ## 📋 Executive Summary</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **• Tesla diverged early.** While most EV brands followed a gradual growth curve, Tesla entered and exited its surge phase earlier – suggesting a sharper, brand-specific trajectory.\</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **• Price sensitivity varies.** Most segments showed textbook behavior: as listings increased, prices fell. Tesla, by contrast, remained price-stable – pointing to centralized pricing or brand insulation.\</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **• Timing overlaps with political signals.** The most significant structural shifts in volume occurred around the same time as Musk’s Trump endorsement – not proof of causation, but enough to warrant further scrutiny.\</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **• Tesla breaks the model.** Statistical models fit well for most segments, but Tesla’s higher residual error and flatter price–volume relationship point to episodic behavior and distinct market logic.\</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **• Implication: Watch Tesla.** Real-time monitoring of brand-specific shifts could provide a competitive edge – especially when sentiment and leadership cues drive market volatility.</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="fu"># 🎯 Objective</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>Explore shifts in the Danish used car market during 2024–2025, with a focus on Tesla’s behavior in response to political signals – especially Elon Musk’s endorsement of Donald Trump.</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>The project uses a retrospective lens to illustrate how structural shifts can be surfaced early with the right data tooling. The key idea: timely insight is possible – but requires tracking and attention.</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="fu"># 🧪 Setup</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>All required packages are loaded in the processing chunk below. No special configurations were needed for this analysis. The document runs entirely within a local R environment using Quarto.</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(zoo)</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(segmented)</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="co"># Data</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"~/Desktop/wasteson/TrackSights/data/bilbasen/trumpmusktesla/Bilbasen biler 1903 2024-kopi.xlsx"</span>)</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> y <span class="sc">%&gt;%</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>    <span class="at">date =</span> <span class="fu">dmy_hms</span>(CreatedDate),</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>    <span class="at">month =</span> <span class="fu">floor_date</span>(date, <span class="st">"month"</span>)</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>start_date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2024-04-01"</span>)</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>end_date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2025-03-14"</span>)</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>market_data <span class="ot">&lt;-</span> y <span class="sc">%&gt;%</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(PriceType <span class="sc">==</span> <span class="st">"RetailPrice"</span>, date <span class="sc">&gt;=</span> start_date <span class="sc">&amp;</span> date <span class="sc">&lt;=</span> end_date) <span class="sc">%&gt;%</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>    <span class="at">week =</span> <span class="fu">floor_date</span>(date, <span class="st">"week"</span>),</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>    <span class="at">fuel_group =</span> <span class="fu">case_when</span>(</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_to_lower</span>(FuelType) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"el"</span>, <span class="st">"electric"</span>) <span class="sc">~</span> <span class="st">"Electric"</span>,</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Fossil"</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>    <span class="at">segment =</span> <span class="fu">case_when</span>(</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>      make <span class="sc">==</span> <span class="st">"Tesla"</span> <span class="sc">~</span> <span class="st">"Tesla"</span>,</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>      make <span class="sc">==</span> <span class="st">"VW"</span> <span class="sc">&amp;</span> <span class="fu">str_detect</span>(model, <span class="st">"^ID</span><span class="sc">\\</span><span class="st">."</span>) <span class="sc">~</span> <span class="st">"VW ID"</span>,</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>      fuel_group <span class="sc">==</span> <span class="st">"Electric"</span> <span class="sc">~</span> <span class="st">"Electric vehicles"</span>,</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>      fuel_group <span class="sc">==</span> <span class="st">"Fossil"</span> <span class="sc">~</span> <span class="st">"Fossil vehicles"</span>,</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Other"</span></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>events <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>  <span class="at">label =</span> <span class="fu">c</span>(<span class="st">"Musk backs Trump"</span>, <span class="st">"Trump elected"</span>, <span class="st">"Trump inaugurated"</span>),</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>  <span class="at">date =</span> <span class="fu">as.POSIXct</span>(<span class="fu">c</span>(<span class="st">"2024-07-13"</span>, <span class="st">"2024-11-05"</span>, <span class="st">"2025-01-15"</span>))</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter data for relevant time period and prepare segment labels</span></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>start_date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2024-04-01"</span>)</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>end_date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2025-03-14"</span>)</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>filtered_data <span class="ot">&lt;-</span> y <span class="sc">%&gt;%</span></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(PriceType <span class="sc">==</span> <span class="st">"RetailPrice"</span>, date <span class="sc">&gt;=</span> start_date <span class="sc">&amp;</span> date <span class="sc">&lt;=</span> end_date) <span class="sc">%&gt;%</span></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>    <span class="at">week =</span> <span class="fu">floor_date</span>(date, <span class="st">"week"</span>),</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>    <span class="at">fuel_group =</span> <span class="fu">case_when</span>(</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_to_lower</span>(FuelType) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"el"</span>, <span class="st">"electric"</span>) <span class="sc">~</span> <span class="st">"Electric"</span>,</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Fossil"</span></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>    <span class="at">segment =</span> <span class="fu">case_when</span>(</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>      make <span class="sc">==</span> <span class="st">"Tesla"</span> <span class="sc">~</span> <span class="st">"Tesla"</span>,</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>      make <span class="sc">==</span> <span class="st">"VW"</span> <span class="sc">&amp;</span> <span class="fu">str_detect</span>(model, <span class="st">"^ID</span><span class="sc">\\</span><span class="st">."</span>) <span class="sc">~</span> <span class="st">"VW ID"</span>,</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>      fuel_group <span class="sc">==</span> <span class="st">"Electric"</span> <span class="sc">~</span> <span class="st">"Electric vehicles"</span>,</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>      fuel_group <span class="sc">==</span> <span class="st">"Fossil"</span> <span class="sc">~</span> <span class="st">"Fossil vehicles"</span>,</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Other"</span></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="fu"># 📘 Synopsis</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>This analysis explores structural shifts in the Danish used car market during 2024–2025, with a specific focus on Tesla's behavior relative to comparable brands. Our objective is twofold: to identify when significant changes in market volume occurred, and to assess whether Tesla responded differently to political signals – especially Elon Musk’s endorsement of Donald Trump.</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>Using weekly listing data from Bilbasen, we segmented the market by fuel type and brand, indexed volumes to a common baseline, and applied segmented regression to detect structural breakpoints in listing trends.</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>Tesla entered its surge phase slightly later (around week 23), but its second structural shift occurred earlier (week 36 vs. 38 for others). This indicates a faster transition through distinct growth phases – not a shorter growth period, but a more compressed and intense trajectory.</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>While we cannot directly attribute Tesla’s movements to political events, the brand clearly diverged from peer behavior – both in timing and intensity. The temporal overlap with high-profile endorsements may be coincidental, or it may point to brand-specific sensitivity to external signals – such as consumer sentiment or leadership cues.</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>Price data reinforce this difference: most segments saw declining prices as supply grew, but Tesla remained remarkably price-stable – hinting at a different dynamic at play. This divergence opens the door for deeper questions: Is it brand loyalty? Centralized pricing? Political sentiment? The pattern is visible – the mechanism, less so.</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>Overall, the analysis shows that structural changes were not only measurable – they were visible as they unfolded. Had this data been monitored in real time, a market actor could have:\</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>– Identified the emerging shift before it peaked\</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>– Reacted with smarter inventory or pricing moves\</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>– Asked sharper questions while competitors were still catching up</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>In a market as volatile and sentiment-driven as used EVs, timely insight is not a luxury – it’s an edge.</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a><span class="fu"># 🧪 Data Processing</span></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>This analysis is based on listing data from the Danish used car marketplace Bilbasen, extracted via TrackSights. The dataset spans from April 1, 2024, to March 14, 2025, and includes only retail listings.</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>We performed the following processing steps:</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>Date parsing and filtering Listings were filtered to include only those with a valid RetailPrice and dates within the analysis window.</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>Fuel type classification Cars were grouped into two fuel groups based on FuelType: • Electric • Fossil (all non-electric drivetrains)</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>Segment definition Based on brand and model, we created five analytical segments: Tesla (all models), VW ID (ID.3, ID.4, ID.5), Skoda Enyaq, electric vehicles, and fossil vehicles. In addition, a “Total market” segment was constructed for broader context.</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>Weekly aggregation Listings were grouped by week using floor_date(), and smoothed using rolling averages where relevant.</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>Indexing Volumes were normalized to an index (Week 1 = 100) per segment. This allows direct comparison of relative change over time.</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>Events overlay Key political events were added for context: • July 13, 2024 – Elon Musk publicly supports Donald Trump • November 5, 2024 – Trump wins the U.S. election • January 15, 2025 – Trump is inaugurated</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a><span class="in">```{r data-processing, include=FALSE}</span></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a><span class="in"># Packages</span></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a><span class="in">library(readxl)</span></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="in">library(dplyr)</span></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a><span class="in">library(lubridate)</span></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="in">library(ggplot2)</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a><span class="in">library(scales)</span></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a><span class="in">library(tidyr)</span></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a><span class="in">library(ggrepel)</span></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a><span class="in">library(stringr)</span></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a><span class="in">library(knitr)</span></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="in">library(zoo)</span></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a><span class="in">library(segmented)</span></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a><span class="in">library(purrr)</span></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a><span class="in"># Load data</span></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a><span class="in">y &lt;- read_excel("~/Desktop/wasteson/TrackSights/data/bilbasen/trumpmusktesla/Bilbasen biler 1903 2024-kopi.xlsx")</span></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="in"># Parse and filter dates</span></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a><span class="in">y &lt;- y %&gt;%</span></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a><span class="in">  mutate(</span></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a><span class="in">    date = dmy_hms(CreatedDate),</span></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a><span class="in">    month = floor_date(date, "month")</span></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a><span class="in">start_date &lt;- as.Date("2024-04-01")</span></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="in">end_date &lt;- as.Date("2025-03-14")</span></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="in"># Filter and segment</span></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="in">market_data &lt;- y %&gt;%</span></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="in">  filter(PriceType == "RetailPrice", date &gt;= start_date &amp; date &lt;= end_date) %&gt;%</span></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="in">  mutate(</span></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a><span class="in">    week = floor_date(date, "week"),</span></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a><span class="in">    fuel_group = case_when(</span></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a><span class="in">      str_to_lower(FuelType) %in% c("el", "electric") ~ "Electric",</span></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a><span class="in">      TRUE ~ "Fossil"</span></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a><span class="in">    ),</span></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a><span class="in">    segment = case_when(</span></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a><span class="in">      make == "Tesla" ~ "Tesla",</span></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a><span class="in">      make == "VW" &amp; str_detect(model, "^ID\\.") ~ "VW ID",</span></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a><span class="in">      fuel_group == "Electric" ~ "Electric vehicles",</span></span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a><span class="in">      fuel_group == "Fossil" ~ "Fossil vehicles",</span></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a><span class="in">      TRUE ~ "Other"</span></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a><span class="in">    )</span></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a><span class="in"># Aggregate volumes</span></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a><span class="in">volume_by_segment &lt;- market_data %&gt;%</span></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a><span class="in">  filter(segment %in% c("Tesla", "VW ID", "Electric vehicles", "Fossil vehicles")) %&gt;%</span></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a><span class="in">  count(week, segment)</span></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a><span class="in">volume_total &lt;- market_data %&gt;%</span></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a><span class="in">  count(week) %&gt;%</span></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a><span class="in">  mutate(segment = "Total market")</span></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a><span class="in"># Combine</span></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a><span class="in">volume_all &lt;- bind_rows(volume_by_segment, volume_total)</span></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a><span class="in"># Index volume</span></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a><span class="in">volume_indexed &lt;- volume_all %&gt;%</span></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a><span class="in">  group_by(segment) %&gt;%</span></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a><span class="in">  arrange(week) %&gt;%</span></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a><span class="in">  mutate(index = (n / first(n)) * 100) %&gt;%</span></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a><span class="in">  ungroup()</span></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a><span class="in"># Event timeline</span></span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a><span class="in">events &lt;- tibble::tibble(</span></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="in">  label = c("Musk backs Trump", "Trump elected", "Trump inaugurated"),</span></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a><span class="in">  date = as.POSIXct(c("2024-07-13", "2024-11-05", "2025-01-15"))</span></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a><span class="fu"># 📊 Results</span></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a><span class="fu">## 📈 Market overview – Total vs Electric vs Fossil</span></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>The chart below shows the relative development in listing volume for fossil vehicles, electric vehicles, and the total used car market in Denmark – all indexed to April 2024 (week 1 = 100). A dramatic shift is visible from late summer 2024, with electric vehicles leading the surge.</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a>***Note on indexing**: The following charts use indexed volumes (Week 1 = 100) to show relative changes over time. This means we are comparing growth patterns – not absolute volumes. For example, Tesla may appear to outpace the EV market, but this reflects faster growth from a smaller base, not a larger total volume.*</span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare volume_primary before plotting</span></span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter relevant segments</span></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>volume_segment <span class="ot">&lt;-</span> filtered_data <span class="sc">%&gt;%</span></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(segment <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Electric vehicles"</span>, <span class="st">"Fossil vehicles"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(week, segment)</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a>volume_total <span class="ot">&lt;-</span> filtered_data <span class="sc">%&gt;%</span></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(week) <span class="sc">%&gt;%</span></span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">segment =</span> <span class="st">"Total market"</span>)</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine and calculate index</span></span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a>volume_primary <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(volume_segment, volume_total) <span class="sc">%&gt;%</span></span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(segment) <span class="sc">%&gt;%</span></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(week) <span class="sc">%&gt;%</span></span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">index =</span> (n <span class="sc">/</span> <span class="fu">first</span>(n)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 9</span></span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Indexed listing volume: Total vs Fossil vs Electric (Retail only, Index = 100 in April 2024)"</span></span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(volume_primary, <span class="fu">aes</span>(<span class="at">x =</span> week, <span class="at">y =</span> index, <span class="at">color =</span> segment)) <span class="sc">+</span></span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="fl">1.3</span>) <span class="sc">+</span></span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> events, <span class="fu">aes</span>(<span class="at">xintercept =</span> date), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> events, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> <span class="cn">Inf</span>, <span class="at">label =</span> label),</span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a>            <span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">hjust =</span> <span class="fl">1.1</span>,</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a>            <span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Total market"</span> <span class="ot">=</span> <span class="st">"#00c0c7"</span>,</span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Electric vehicles"</span> <span class="ot">=</span> <span class="st">"#FFDD57"</span>,</span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Fossil vehicles"</span> <span class="ot">=</span> <span class="st">"#FF6B6B"</span></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Indexed listing volume – Market overview"</span>,</span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Total vs Electric vs Fossil (Retail only, Index = 100 in April 2024)"</span>,</span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Week"</span>,</span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Volume index"</span>,</span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Segment"</span></span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#1e1e1e"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#1e1e1e"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">"#444444"</span>),</span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a>    <span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"white"</span>),</span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"white"</span>),</span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#1e1e1e"</span>),</span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.key =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#1e1e1e"</span>)</span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a><span class="fu">## 🔍 Brand comparison – Tesla vs VW ID</span></span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a>Direct volume comparison between two comparable brands. Tesla displays more volatility and sharper surges, suggesting a faster transition once growth begins.</span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a><span class="in">```{r volume_tesla_vw, fig.width=9, fig.height=5, echo=FALSE, fig.cap="📈 Indexed listing volume: Tesla vs VW ID (Retail only, Index = 100 in April 2024)"}</span></span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a><span class="in">volume_focus &lt;- filtered_data %&gt;%</span></span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a><span class="in">  filter(segment %in% c("Tesla", "VW ID")) %&gt;%</span></span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a><span class="in">  count(week, segment) %&gt;%</span></span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a><span class="in">  group_by(segment) %&gt;%</span></span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a><span class="in">  arrange(week) %&gt;%</span></span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a><span class="in">  mutate(index = (n / first(n)) * 100) %&gt;%</span></span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a><span class="in">  ungroup()</span></span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(volume_focus, aes(x = week, y = index, color = segment)) +</span></span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_line(size = 1.3) +</span></span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_vline(data = events, aes(xintercept = date), linetype = "dashed", color = "white") +</span></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_text(data = events, aes(x = date, y = Inf, label = label),</span></span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a><span class="in">            angle = 90, vjust = -0.5, hjust = 1.1,</span></span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a><span class="in">            size = 3.5, color = "white", inherit.aes = FALSE) +</span></span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a><span class="in">  scale_color_manual(values = c(</span></span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a><span class="in">    "Tesla" = "#6BE7C2",</span></span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a><span class="in">    "VW ID" = "#8BC34A"</span></span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a><span class="in">  )) +</span></span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a><span class="in">  labs(</span></span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a><span class="in">    title = "Indexed listing volume – Tesla vs VW ID",</span></span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a><span class="in">    subtitle = "Retail listings, relative to Apr 2024 = 100",</span></span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a><span class="in">    x = "Week",</span></span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a><span class="in">    y = "Volume index",</span></span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a><span class="in">    color = "Brand"</span></span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a><span class="in">  ) +</span></span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a><span class="in">  theme_minimal(base_size = 13) +</span></span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a><span class="in">  theme(</span></span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a><span class="in">    plot.background = element_rect(fill = "#1e1e1e", color = NA),</span></span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.background = element_rect(fill = "#1e1e1e", color = NA),</span></span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.major = element_line(color = "#444444"),</span></span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.minor = element_blank(),</span></span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a><span class="in">    text = element_text(color = "white"),</span></span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a><span class="in">    axis.text = element_text(color = "white"),</span></span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.key = element_rect(fill = "#1e1e1e")</span></span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a><span class="fu">## 📐 Structural breakpoints – Segmented regression</span></span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a>When did volume behavior change?\</span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a>We compare Tesla, VW ID, Skoda Enyaq, the total market, and broader EVs using segmented regression.\</span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a>Both one- and two-breakpoint models were tested to assess structural shifts in listing volumes.</span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a>**Findings**\</span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a>The one-breakpoint model suggested that Tesla shifted earlier than the rest – with a change around week 30, while other segments (VW ID, Enyaq, EVs, total market) shifted later, typically in week 38.</span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a>To test this further, we applied a two-breakpoint model to explore potential phase transitions:</span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Tesla entered its growth phase slightly after others (week 23)\</span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>But its second structural shift occurred earlier (week 36 vs. week 38 for peers)</span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a>**Interpretation**\</span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a>Tesla’s volume curve was more compressed and sharper, suggesting a distinct growth pattern:\</span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a>⚡ Not out of sync – but different. This supports the idea of brand-specific drivers, rather than a uniform EV market trend.</span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a><span class="in">```{r load_packages, include=FALSE}</span></span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a><span class="in">library(dplyr)</span></span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a><span class="in">library(ggplot2)</span></span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a><span class="in">library(segmented)</span></span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a><span class="in">library(knitr)</span></span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a><span class="in">library(tibble)</span></span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a><span class="in">```{r prepare_data}</span></span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a><span class="in">prepare_segment_data &lt;- function(df, segment_label) {</span></span>
<span id="cb1-370"><a href="#cb1-370" aria-hidden="true" tabindex="-1"></a><span class="in">  df %&gt;%</span></span>
<span id="cb1-371"><a href="#cb1-371" aria-hidden="true" tabindex="-1"></a><span class="in">    filter(segment == segment_label) %&gt;%</span></span>
<span id="cb1-372"><a href="#cb1-372" aria-hidden="true" tabindex="-1"></a><span class="in">    arrange(week) %&gt;%</span></span>
<span id="cb1-373"><a href="#cb1-373" aria-hidden="true" tabindex="-1"></a><span class="in">    mutate(</span></span>
<span id="cb1-374"><a href="#cb1-374" aria-hidden="true" tabindex="-1"></a><span class="in">      week_num = as.numeric(difftime(week, min(week), units = "weeks")),</span></span>
<span id="cb1-375"><a href="#cb1-375" aria-hidden="true" tabindex="-1"></a><span class="in">      index = (n / first(n)) * 100</span></span>
<span id="cb1-376"><a href="#cb1-376" aria-hidden="true" tabindex="-1"></a><span class="in">    )</span></span>
<span id="cb1-377"><a href="#cb1-377" aria-hidden="true" tabindex="-1"></a><span class="in">}</span></span>
<span id="cb1-378"><a href="#cb1-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-379"><a href="#cb1-379" aria-hidden="true" tabindex="-1"></a><span class="in">tesla_data &lt;- prepare_segment_data(volume_all, "Tesla")</span></span>
<span id="cb1-380"><a href="#cb1-380" aria-hidden="true" tabindex="-1"></a><span class="in">vwid_data  &lt;- prepare_segment_data(volume_all, "VW ID")</span></span>
<span id="cb1-381"><a href="#cb1-381" aria-hidden="true" tabindex="-1"></a><span class="in">ev_data    &lt;- prepare_segment_data(volume_all, "Electric vehicles")</span></span>
<span id="cb1-382"><a href="#cb1-382" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-383"><a href="#cb1-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-384"><a href="#cb1-384" aria-hidden="true" tabindex="-1"></a><span class="in">```{r segmented_models}</span></span>
<span id="cb1-385"><a href="#cb1-385" aria-hidden="true" tabindex="-1"></a><span class="in">tesla_seg &lt;- segmented(lm(index ~ week_num, data = tesla_data), seg.Z = ~week_num, psi = c(20, 35))</span></span>
<span id="cb1-386"><a href="#cb1-386" aria-hidden="true" tabindex="-1"></a><span class="in">vwid_seg  &lt;- segmented(lm(index ~ week_num, data = vwid_data),  seg.Z = ~week_num, psi = c(20, 35))</span></span>
<span id="cb1-387"><a href="#cb1-387" aria-hidden="true" tabindex="-1"></a><span class="in">ev_seg    &lt;- segmented(lm(index ~ week_num, data = ev_data),    seg.Z = ~week_num, psi = c(20, 36))</span></span>
<span id="cb1-388"><a href="#cb1-388" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-389"><a href="#cb1-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-390"><a href="#cb1-390" aria-hidden="true" tabindex="-1"></a><span class="in">```{r breakpoint_table}</span></span>
<span id="cb1-391"><a href="#cb1-391" aria-hidden="true" tabindex="-1"></a><span class="in">compare_models_2breaks &lt;- tibble(</span></span>
<span id="cb1-392"><a href="#cb1-392" aria-hidden="true" tabindex="-1"></a><span class="in">  Segment = c("Tesla", "VW ID", "Electric vehicles"),</span></span>
<span id="cb1-393"><a href="#cb1-393" aria-hidden="true" tabindex="-1"></a><span class="in">  Breakpoints = c(</span></span>
<span id="cb1-394"><a href="#cb1-394" aria-hidden="true" tabindex="-1"></a><span class="in">    paste(round(tesla_seg$psi[, "Est."], 1), collapse = ", "),</span></span>
<span id="cb1-395"><a href="#cb1-395" aria-hidden="true" tabindex="-1"></a><span class="in">    paste(round(vwid_seg$psi[, "Est."], 1), collapse = ", "),</span></span>
<span id="cb1-396"><a href="#cb1-396" aria-hidden="true" tabindex="-1"></a><span class="in">    paste(round(ev_seg$psi[, "Est."], 1), collapse = ", ")</span></span>
<span id="cb1-397"><a href="#cb1-397" aria-hidden="true" tabindex="-1"></a><span class="in">  ),</span></span>
<span id="cb1-398"><a href="#cb1-398" aria-hidden="true" tabindex="-1"></a><span class="in">  `R²` = c(</span></span>
<span id="cb1-399"><a href="#cb1-399" aria-hidden="true" tabindex="-1"></a><span class="in">    round(summary(tesla_seg)$r.squared, 2),</span></span>
<span id="cb1-400"><a href="#cb1-400" aria-hidden="true" tabindex="-1"></a><span class="in">    round(summary(vwid_seg)$r.squared, 2),</span></span>
<span id="cb1-401"><a href="#cb1-401" aria-hidden="true" tabindex="-1"></a><span class="in">    round(summary(ev_seg)$r.squared, 2)</span></span>
<span id="cb1-402"><a href="#cb1-402" aria-hidden="true" tabindex="-1"></a><span class="in">  ),</span></span>
<span id="cb1-403"><a href="#cb1-403" aria-hidden="true" tabindex="-1"></a><span class="in">  `Residual Std. Error` = c(</span></span>
<span id="cb1-404"><a href="#cb1-404" aria-hidden="true" tabindex="-1"></a><span class="in">    round(summary(tesla_seg)$sigma, 2),</span></span>
<span id="cb1-405"><a href="#cb1-405" aria-hidden="true" tabindex="-1"></a><span class="in">    round(summary(vwid_seg)$sigma, 2),</span></span>
<span id="cb1-406"><a href="#cb1-406" aria-hidden="true" tabindex="-1"></a><span class="in">    round(summary(ev_seg)$sigma, 2)</span></span>
<span id="cb1-407"><a href="#cb1-407" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-408"><a href="#cb1-408" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb1-409"><a href="#cb1-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-410"><a href="#cb1-410" aria-hidden="true" tabindex="-1"></a><span class="in">kable(</span></span>
<span id="cb1-411"><a href="#cb1-411" aria-hidden="true" tabindex="-1"></a><span class="in">  compare_models_2breaks,</span></span>
<span id="cb1-412"><a href="#cb1-412" aria-hidden="true" tabindex="-1"></a><span class="in">  caption = "Segmented regression (2 breakpoints): Tesla, VW ID, Electric vehicles",</span></span>
<span id="cb1-413"><a href="#cb1-413" aria-hidden="true" tabindex="-1"></a><span class="in">  col.names = c("Segment", "Breakpoints", "R²", "Residual Std. Error")</span></span>
<span id="cb1-414"><a href="#cb1-414" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb1-415"><a href="#cb1-415" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-416"><a href="#cb1-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-417"><a href="#cb1-417" aria-hidden="true" tabindex="-1"></a>Model interpretation: Tesla vs. peers</span>
<span id="cb1-418"><a href="#cb1-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-419"><a href="#cb1-419" aria-hidden="true" tabindex="-1"></a>While all models exhibit a good fit (R² <span class="sc">\&gt;</span> 0.90), there are notable differences in residual error.</span>
<span id="cb1-420"><a href="#cb1-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-421"><a href="#cb1-421" aria-hidden="true" tabindex="-1"></a>Tesla shows the **lowest R² (0.90)** and **highest residual standard error (1700)** compared to VW ID (R² = 0.93, RSE ≈ 888) and the broader EV segment (R² = 0.95, RSE ≈ 1188).</span>
<span id="cb1-422"><a href="#cb1-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-423"><a href="#cb1-423" aria-hidden="true" tabindex="-1"></a>This suggests that Tesla’s volume curve is **less well captured by a simple two-phase model**, and likely reflects:</span>
<span id="cb1-424"><a href="#cb1-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-425"><a href="#cb1-425" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Sharper transitions** in listing behavior (e.g., price cuts, sudden demand surges)</span>
<span id="cb1-426"><a href="#cb1-426" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**More episodic dynamics**, potentially driven by brand-specific strategies</span>
<span id="cb1-427"><a href="#cb1-427" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Outlier events** or volatility not present in other EV segments</span>
<span id="cb1-428"><a href="#cb1-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-429"><a href="#cb1-429" aria-hidden="true" tabindex="-1"></a>🧠 *Interpretation:*\</span>
<span id="cb1-430"><a href="#cb1-430" aria-hidden="true" tabindex="-1"></a>The higher residual variation reinforces the idea that Tesla’s structural shifts follow a **more distinct and compressed pattern**, which supports the argument for **brand-specific timing mechanisms** rather than a uniform EV market trend.</span>
<span id="cb1-431"><a href="#cb1-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-432"><a href="#cb1-432" aria-hidden="true" tabindex="-1"></a><span class="fu">## Timing of breakpoints in listing trends</span></span>
<span id="cb1-433"><a href="#cb1-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-434"><a href="#cb1-434" aria-hidden="true" tabindex="-1"></a><span class="in">```{r breakpoint_plot, fig.cap="Timing of structural shifts in listing volume – segmented regression breakpoints (2 per brand)", fig.width=9, fig.height=5}</span></span>
<span id="cb1-435"><a href="#cb1-435" aria-hidden="true" tabindex="-1"></a><span class="in">breakpoint_df &lt;- tibble(</span></span>
<span id="cb1-436"><a href="#cb1-436" aria-hidden="true" tabindex="-1"></a><span class="in">  segment = c(rep("Tesla", 2), rep("VW ID", 2), rep("Electric vehicles", 2)),</span></span>
<span id="cb1-437"><a href="#cb1-437" aria-hidden="true" tabindex="-1"></a><span class="in">  breakpoint = c(</span></span>
<span id="cb1-438"><a href="#cb1-438" aria-hidden="true" tabindex="-1"></a><span class="in">    tesla_seg$psi[, "Est."],</span></span>
<span id="cb1-439"><a href="#cb1-439" aria-hidden="true" tabindex="-1"></a><span class="in">    vwid_seg$psi[, "Est."],</span></span>
<span id="cb1-440"><a href="#cb1-440" aria-hidden="true" tabindex="-1"></a><span class="in">    ev_seg$psi[, "Est."]</span></span>
<span id="cb1-441"><a href="#cb1-441" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-442"><a href="#cb1-442" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb1-443"><a href="#cb1-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-444"><a href="#cb1-444" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(breakpoint_df, aes(x = breakpoint, y = segment, color = segment)) +</span></span>
<span id="cb1-445"><a href="#cb1-445" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_point(size = 4) +</span></span>
<span id="cb1-446"><a href="#cb1-446" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_line(aes(group = segment), linewidth = 1.2) +</span></span>
<span id="cb1-447"><a href="#cb1-447" aria-hidden="true" tabindex="-1"></a><span class="in">  scale_color_manual(values = c(</span></span>
<span id="cb1-448"><a href="#cb1-448" aria-hidden="true" tabindex="-1"></a><span class="in">    "Tesla" = "#6BE7C2",</span></span>
<span id="cb1-449"><a href="#cb1-449" aria-hidden="true" tabindex="-1"></a><span class="in">    "VW ID" = "#8BC34A",</span></span>
<span id="cb1-450"><a href="#cb1-450" aria-hidden="true" tabindex="-1"></a><span class="in">    "Electric vehicles" = "#FFDD57"</span></span>
<span id="cb1-451"><a href="#cb1-451" aria-hidden="true" tabindex="-1"></a><span class="in">  )) +</span></span>
<span id="cb1-452"><a href="#cb1-452" aria-hidden="true" tabindex="-1"></a><span class="in">  labs(</span></span>
<span id="cb1-453"><a href="#cb1-453" aria-hidden="true" tabindex="-1"></a><span class="in">    title = "Timing of structural shifts in listing volume",</span></span>
<span id="cb1-454"><a href="#cb1-454" aria-hidden="true" tabindex="-1"></a><span class="in">    subtitle = "Segmented regression breakpoints – 2 per brand",</span></span>
<span id="cb1-455"><a href="#cb1-455" aria-hidden="true" tabindex="-1"></a><span class="in">    x = "Estimated breakpoint (week number from April 1, 2024)",</span></span>
<span id="cb1-456"><a href="#cb1-456" aria-hidden="true" tabindex="-1"></a><span class="in">    y = NULL,</span></span>
<span id="cb1-457"><a href="#cb1-457" aria-hidden="true" tabindex="-1"></a><span class="in">    color = "Segment"</span></span>
<span id="cb1-458"><a href="#cb1-458" aria-hidden="true" tabindex="-1"></a><span class="in">  ) +</span></span>
<span id="cb1-459"><a href="#cb1-459" aria-hidden="true" tabindex="-1"></a><span class="in">  scale_x_continuous(breaks = seq(20, 40, 2)) +</span></span>
<span id="cb1-460"><a href="#cb1-460" aria-hidden="true" tabindex="-1"></a><span class="in">  theme_minimal(base_size = 13) +</span></span>
<span id="cb1-461"><a href="#cb1-461" aria-hidden="true" tabindex="-1"></a><span class="in">  theme(</span></span>
<span id="cb1-462"><a href="#cb1-462" aria-hidden="true" tabindex="-1"></a><span class="in">    plot.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-463"><a href="#cb1-463" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-464"><a href="#cb1-464" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.major = element_line(color = "#444444"),</span></span>
<span id="cb1-465"><a href="#cb1-465" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.minor = element_blank(),</span></span>
<span id="cb1-466"><a href="#cb1-466" aria-hidden="true" tabindex="-1"></a><span class="in">    text = element_text(color = "white"),</span></span>
<span id="cb1-467"><a href="#cb1-467" aria-hidden="true" tabindex="-1"></a><span class="in">    axis.text = element_text(color = "white"),</span></span>
<span id="cb1-468"><a href="#cb1-468" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-469"><a href="#cb1-469" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.key = element_rect(fill = "#1e1e1e")</span></span>
<span id="cb1-470"><a href="#cb1-470" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-471"><a href="#cb1-471" aria-hidden="true" tabindex="-1"></a><span class="in">  </span></span>
<span id="cb1-472"><a href="#cb1-472" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-473"><a href="#cb1-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-474"><a href="#cb1-474" aria-hidden="true" tabindex="-1"></a>"Breakpoints show a more compressed transition for Tesla: it entered its growth phase slightly later, but exhibited an earlier structural shift in pattern. Peers (VW ID, EV market) followed a broader, more aligned trajectory across the period."</span>
<span id="cb1-475"><a href="#cb1-475" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-476"><a href="#cb1-476" aria-hidden="true" tabindex="-1"></a><span class="fu"># 💸 Price dynamics</span></span>
<span id="cb1-477"><a href="#cb1-477" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-478"><a href="#cb1-478" aria-hidden="true" tabindex="-1"></a>How did prices respond to the volume shift?</span>
<span id="cb1-479"><a href="#cb1-479" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-480"><a href="#cb1-480" aria-hidden="true" tabindex="-1"></a>This section investigates whether listing volumes and median retail prices moved in tandem – or diverged – across segments.</span>
<span id="cb1-481"><a href="#cb1-481" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-482"><a href="#cb1-482" aria-hidden="true" tabindex="-1"></a>We apply three main analytical lenses in the main section:</span>
<span id="cb1-483"><a href="#cb1-483" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-484"><a href="#cb1-484" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>**Correlation analysis** – do higher volumes coincide with lower prices?\</span>
<span id="cb1-485"><a href="#cb1-485" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**Price–volume scatterplots** – visualizing the relationship\</span>
<span id="cb1-486"><a href="#cb1-486" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>**LOESS smoothing** – uncovering broader structural price trends</span>
<span id="cb1-487"><a href="#cb1-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-488"><a href="#cb1-488" aria-hidden="true" tabindex="-1"></a>📎 *Supplementary figures are available in the Appendix.*</span>
<span id="cb1-489"><a href="#cb1-489" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-490"><a href="#cb1-490" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-491"><a href="#cb1-491" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-492"><a href="#cb1-492" aria-hidden="true" tabindex="-1"></a><span class="in">```{r prepare_price_dynamics, include=FALSE}</span></span>
<span id="cb1-493"><a href="#cb1-493" aria-hidden="true" tabindex="-1"></a><span class="in"># 1. Medianpris for hele markedet</span></span>
<span id="cb1-494"><a href="#cb1-494" aria-hidden="true" tabindex="-1"></a><span class="in">price_trend &lt;- market_data %&gt;%</span></span>
<span id="cb1-495"><a href="#cb1-495" aria-hidden="true" tabindex="-1"></a><span class="in">  filter(segment %in% c("Total market", "Electric vehicles", "Fossil vehicles")) %&gt;%</span></span>
<span id="cb1-496"><a href="#cb1-496" aria-hidden="true" tabindex="-1"></a><span class="in">  filter(!is.na(Price), Price &gt; 10000) %&gt;%</span></span>
<span id="cb1-497"><a href="#cb1-497" aria-hidden="true" tabindex="-1"></a><span class="in">  group_by(week, segment) %&gt;%</span></span>
<span id="cb1-498"><a href="#cb1-498" aria-hidden="true" tabindex="-1"></a><span class="in">  summarise(median_price = median(Price), .groups = "drop")</span></span>
<span id="cb1-499"><a href="#cb1-499" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-500"><a href="#cb1-500" aria-hidden="true" tabindex="-1"></a><span class="in"># 2. Medianpris for Tesla og VW ID</span></span>
<span id="cb1-501"><a href="#cb1-501" aria-hidden="true" tabindex="-1"></a><span class="in">price_focus_weekly &lt;- market_data %&gt;%</span></span>
<span id="cb1-502"><a href="#cb1-502" aria-hidden="true" tabindex="-1"></a><span class="in">  filter(segment %in% c("Tesla", "VW ID"), !is.na(Price), Price &gt; 10000) %&gt;%</span></span>
<span id="cb1-503"><a href="#cb1-503" aria-hidden="true" tabindex="-1"></a><span class="in">  group_by(week, segment) %&gt;%</span></span>
<span id="cb1-504"><a href="#cb1-504" aria-hidden="true" tabindex="-1"></a><span class="in">  summarise(median_price = median(Price), .groups = "drop")</span></span>
<span id="cb1-505"><a href="#cb1-505" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-506"><a href="#cb1-506" aria-hidden="true" tabindex="-1"></a><span class="in"># 3. Volum vs pris per uke</span></span>
<span id="cb1-507"><a href="#cb1-507" aria-hidden="true" tabindex="-1"></a><span class="in">vol_vs_price &lt;- market_data %&gt;%</span></span>
<span id="cb1-508"><a href="#cb1-508" aria-hidden="true" tabindex="-1"></a><span class="in">  filter(segment %in% c("Tesla", "VW ID", "Electric vehicles", "Fossil vehicles")) %&gt;%</span></span>
<span id="cb1-509"><a href="#cb1-509" aria-hidden="true" tabindex="-1"></a><span class="in">  filter(!is.na(Price), Price &gt; 10000) %&gt;%</span></span>
<span id="cb1-510"><a href="#cb1-510" aria-hidden="true" tabindex="-1"></a><span class="in">  group_by(segment, week) %&gt;%</span></span>
<span id="cb1-511"><a href="#cb1-511" aria-hidden="true" tabindex="-1"></a><span class="in">  summarise(</span></span>
<span id="cb1-512"><a href="#cb1-512" aria-hidden="true" tabindex="-1"></a><span class="in">    n = n(),</span></span>
<span id="cb1-513"><a href="#cb1-513" aria-hidden="true" tabindex="-1"></a><span class="in">    median_price = median(Price),</span></span>
<span id="cb1-514"><a href="#cb1-514" aria-hidden="true" tabindex="-1"></a><span class="in">    .groups = "drop"</span></span>
<span id="cb1-515"><a href="#cb1-515" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-516"><a href="#cb1-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-517"><a href="#cb1-517" aria-hidden="true" tabindex="-1"></a><span class="in"># 4. Prisindeks (index = 100)</span></span>
<span id="cb1-518"><a href="#cb1-518" aria-hidden="true" tabindex="-1"></a><span class="in">price_index &lt;- market_data %&gt;%</span></span>
<span id="cb1-519"><a href="#cb1-519" aria-hidden="true" tabindex="-1"></a><span class="in">  filter(segment %in% c("Tesla", "VW ID", "Electric vehicles", "Fossil vehicles")) %&gt;%</span></span>
<span id="cb1-520"><a href="#cb1-520" aria-hidden="true" tabindex="-1"></a><span class="in">  filter(!is.na(Price), Price &gt; 10000) %&gt;%</span></span>
<span id="cb1-521"><a href="#cb1-521" aria-hidden="true" tabindex="-1"></a><span class="in">  group_by(segment, week) %&gt;%</span></span>
<span id="cb1-522"><a href="#cb1-522" aria-hidden="true" tabindex="-1"></a><span class="in">  summarise(median_price = median(Price), .groups = "drop") %&gt;%</span></span>
<span id="cb1-523"><a href="#cb1-523" aria-hidden="true" tabindex="-1"></a><span class="in">  group_by(segment) %&gt;%</span></span>
<span id="cb1-524"><a href="#cb1-524" aria-hidden="true" tabindex="-1"></a><span class="in">  arrange(week) %&gt;%</span></span>
<span id="cb1-525"><a href="#cb1-525" aria-hidden="true" tabindex="-1"></a><span class="in">  mutate(price_index = (median_price / first(median_price)) * 100) %&gt;%</span></span>
<span id="cb1-526"><a href="#cb1-526" aria-hidden="true" tabindex="-1"></a><span class="in">  ungroup()</span></span>
<span id="cb1-527"><a href="#cb1-527" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-528"><a href="#cb1-528" aria-hidden="true" tabindex="-1"></a><span class="in"># 5. LOESS-data</span></span>
<span id="cb1-529"><a href="#cb1-529" aria-hidden="true" tabindex="-1"></a><span class="in">price_loess &lt;- market_data %&gt;%</span></span>
<span id="cb1-530"><a href="#cb1-530" aria-hidden="true" tabindex="-1"></a><span class="in">  filter(segment %in% c("Tesla", "VW ID", "Electric vehicles", "Fossil vehicles")) %&gt;%</span></span>
<span id="cb1-531"><a href="#cb1-531" aria-hidden="true" tabindex="-1"></a><span class="in">  filter(!is.na(Price), Price &gt; 10000) %&gt;%</span></span>
<span id="cb1-532"><a href="#cb1-532" aria-hidden="true" tabindex="-1"></a><span class="in">  group_by(week, segment) %&gt;%</span></span>
<span id="cb1-533"><a href="#cb1-533" aria-hidden="true" tabindex="-1"></a><span class="in">  summarise(median_price = median(Price), .groups = "drop")</span></span>
<span id="cb1-534"><a href="#cb1-534" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-535"><a href="#cb1-535" aria-hidden="true" tabindex="-1"></a><span class="in"># 6. Korrelasjonsanalyse</span></span>
<span id="cb1-536"><a href="#cb1-536" aria-hidden="true" tabindex="-1"></a><span class="in">get_correlation &lt;- function(seg) {</span></span>
<span id="cb1-537"><a href="#cb1-537" aria-hidden="true" tabindex="-1"></a><span class="in">  df &lt;- filtered_data %&gt;%</span></span>
<span id="cb1-538"><a href="#cb1-538" aria-hidden="true" tabindex="-1"></a><span class="in">    filter(segment == seg, Price &gt;= 10000) %&gt;%</span></span>
<span id="cb1-539"><a href="#cb1-539" aria-hidden="true" tabindex="-1"></a><span class="in">    mutate(week = floor_date(date, "week")) %&gt;%</span></span>
<span id="cb1-540"><a href="#cb1-540" aria-hidden="true" tabindex="-1"></a><span class="in">    group_by(week) %&gt;%</span></span>
<span id="cb1-541"><a href="#cb1-541" aria-hidden="true" tabindex="-1"></a><span class="in">    summarise(</span></span>
<span id="cb1-542"><a href="#cb1-542" aria-hidden="true" tabindex="-1"></a><span class="in">      volume = n(),</span></span>
<span id="cb1-543"><a href="#cb1-543" aria-hidden="true" tabindex="-1"></a><span class="in">      median_price = median(Price),</span></span>
<span id="cb1-544"><a href="#cb1-544" aria-hidden="true" tabindex="-1"></a><span class="in">      .groups = "drop"</span></span>
<span id="cb1-545"><a href="#cb1-545" aria-hidden="true" tabindex="-1"></a><span class="in">    )</span></span>
<span id="cb1-546"><a href="#cb1-546" aria-hidden="true" tabindex="-1"></a><span class="in">  if (nrow(df) &lt; 5) return(NULL)</span></span>
<span id="cb1-547"><a href="#cb1-547" aria-hidden="true" tabindex="-1"></a><span class="in">  test &lt;- cor.test(df$volume, df$median_price)</span></span>
<span id="cb1-548"><a href="#cb1-548" aria-hidden="true" tabindex="-1"></a><span class="in">  tibble(</span></span>
<span id="cb1-549"><a href="#cb1-549" aria-hidden="true" tabindex="-1"></a><span class="in">    Segment = seg,</span></span>
<span id="cb1-550"><a href="#cb1-550" aria-hidden="true" tabindex="-1"></a><span class="in">    correlation = test$estimate,</span></span>
<span id="cb1-551"><a href="#cb1-551" aria-hidden="true" tabindex="-1"></a><span class="in">    p_value = test$p.value</span></span>
<span id="cb1-552"><a href="#cb1-552" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-553"><a href="#cb1-553" aria-hidden="true" tabindex="-1"></a><span class="in">}</span></span>
<span id="cb1-554"><a href="#cb1-554" aria-hidden="true" tabindex="-1"></a><span class="in">segments_to_analyze &lt;- c("Tesla", "VW ID", "Electric vehicles", "Fossil vehicles")</span></span>
<span id="cb1-555"><a href="#cb1-555" aria-hidden="true" tabindex="-1"></a><span class="in">correlation_results &lt;- purrr::map_dfr(segments_to_analyze, get_correlation)</span></span>
<span id="cb1-556"><a href="#cb1-556" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-557"><a href="#cb1-557" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-558"><a href="#cb1-558" aria-hidden="true" tabindex="-1"></a><span class="fu">## 📊 Correlation: Price vs. Volume</span></span>
<span id="cb1-559"><a href="#cb1-559" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-560"><a href="#cb1-560" aria-hidden="true" tabindex="-1"></a><span class="in">```{r price_correlation}</span></span>
<span id="cb1-561"><a href="#cb1-561" aria-hidden="true" tabindex="-1"></a><span class="in">correlation_results %&gt;%</span></span>
<span id="cb1-562"><a href="#cb1-562" aria-hidden="true" tabindex="-1"></a><span class="in">  knitr::kable(</span></span>
<span id="cb1-563"><a href="#cb1-563" aria-hidden="true" tabindex="-1"></a><span class="in">    caption = "Correlation between weekly listing volume and median retail price",</span></span>
<span id="cb1-564"><a href="#cb1-564" aria-hidden="true" tabindex="-1"></a><span class="in">    digits = 3,</span></span>
<span id="cb1-565"><a href="#cb1-565" aria-hidden="true" tabindex="-1"></a><span class="in">    col.names = c("Segment", "Pearson correlation", "P-value")</span></span>
<span id="cb1-566"><a href="#cb1-566" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-567"><a href="#cb1-567" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-568"><a href="#cb1-568" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-569"><a href="#cb1-569" aria-hidden="true" tabindex="-1"></a>**Interpretation**</span>
<span id="cb1-570"><a href="#cb1-570" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-571"><a href="#cb1-571" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>📉 **Fossil vehicles and EVs**: strong negative correlation → more listings = lower prices\</span>
<span id="cb1-572"><a href="#cb1-572" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>📉 **VW ID**: moderate but significant correlation\</span>
<span id="cb1-573"><a href="#cb1-573" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>➖ **Tesla**: nearly flat, non-significant relationship (r = –0.085, p = 0.595)</span>
<span id="cb1-574"><a href="#cb1-574" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-575"><a href="#cb1-575" aria-hidden="true" tabindex="-1"></a>This suggests that **Tesla’s prices were less sensitive to changes in listing volume**, diverging from other segments.</span>
<span id="cb1-576"><a href="#cb1-576" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-577"><a href="#cb1-577" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-578"><a href="#cb1-578" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-579"><a href="#cb1-579" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-580"><a href="#cb1-580" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-581"><a href="#cb1-581" aria-hidden="true" tabindex="-1"></a><span class="fu">## 🔁 Scatterplot – Volume vs median price for selected brands</span></span>
<span id="cb1-582"><a href="#cb1-582" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-583"><a href="#cb1-583" aria-hidden="true" tabindex="-1"></a><span class="in">```{r price_volume_selected_brands, fig.width=9, fig.height=5, fig.cap="Volume vs. median retail price – Selected brands (Tesla, VW ID, Skoda Enyaq)"}</span></span>
<span id="cb1-584"><a href="#cb1-584" aria-hidden="true" tabindex="-1"></a><span class="in">scatter_brands &lt;- filtered_data %&gt;%</span></span>
<span id="cb1-585"><a href="#cb1-585" aria-hidden="true" tabindex="-1"></a><span class="in">  filter(segment %in% c("Tesla", "VW ID") | (make == "Skoda" &amp; model == "Enyaq")) %&gt;%</span></span>
<span id="cb1-586"><a href="#cb1-586" aria-hidden="true" tabindex="-1"></a><span class="in">  mutate(segment = case_when(</span></span>
<span id="cb1-587"><a href="#cb1-587" aria-hidden="true" tabindex="-1"></a><span class="in">    make == "Skoda" &amp; model == "Enyaq" ~ "Skoda Enyaq",</span></span>
<span id="cb1-588"><a href="#cb1-588" aria-hidden="true" tabindex="-1"></a><span class="in">    TRUE ~ segment</span></span>
<span id="cb1-589"><a href="#cb1-589" aria-hidden="true" tabindex="-1"></a><span class="in">  )) %&gt;%</span></span>
<span id="cb1-590"><a href="#cb1-590" aria-hidden="true" tabindex="-1"></a><span class="in">  group_by(week, segment) %&gt;%</span></span>
<span id="cb1-591"><a href="#cb1-591" aria-hidden="true" tabindex="-1"></a><span class="in">  summarise(</span></span>
<span id="cb1-592"><a href="#cb1-592" aria-hidden="true" tabindex="-1"></a><span class="in">    volume = n(),</span></span>
<span id="cb1-593"><a href="#cb1-593" aria-hidden="true" tabindex="-1"></a><span class="in">    median_price = median(Price, na.rm = TRUE),</span></span>
<span id="cb1-594"><a href="#cb1-594" aria-hidden="true" tabindex="-1"></a><span class="in">    .groups = "drop"</span></span>
<span id="cb1-595"><a href="#cb1-595" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-596"><a href="#cb1-596" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-597"><a href="#cb1-597" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(scatter_brands, aes(x = volume, y = median_price, color = segment)) +</span></span>
<span id="cb1-598"><a href="#cb1-598" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_point(alpha = 0.7, size = 3) +</span></span>
<span id="cb1-599"><a href="#cb1-599" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_smooth(method = "lm", se = FALSE, size = 1.2) +</span></span>
<span id="cb1-600"><a href="#cb1-600" aria-hidden="true" tabindex="-1"></a><span class="in">  scale_color_manual(values = c(</span></span>
<span id="cb1-601"><a href="#cb1-601" aria-hidden="true" tabindex="-1"></a><span class="in">    "Tesla" = "#6BE7C2",</span></span>
<span id="cb1-602"><a href="#cb1-602" aria-hidden="true" tabindex="-1"></a><span class="in">    "VW ID" = "#8BC34A",</span></span>
<span id="cb1-603"><a href="#cb1-603" aria-hidden="true" tabindex="-1"></a><span class="in">    "Skoda Enyaq" = "#FFDD57"</span></span>
<span id="cb1-604"><a href="#cb1-604" aria-hidden="true" tabindex="-1"></a><span class="in">  )) +</span></span>
<span id="cb1-605"><a href="#cb1-605" aria-hidden="true" tabindex="-1"></a><span class="in">  labs(</span></span>
<span id="cb1-606"><a href="#cb1-606" aria-hidden="true" tabindex="-1"></a><span class="in">    title = "Volume vs. median retail price – Selected brands",</span></span>
<span id="cb1-607"><a href="#cb1-607" aria-hidden="true" tabindex="-1"></a><span class="in">    subtitle = "Weekly listings (Retail only)",</span></span>
<span id="cb1-608"><a href="#cb1-608" aria-hidden="true" tabindex="-1"></a><span class="in">    x = "Number of listings",</span></span>
<span id="cb1-609"><a href="#cb1-609" aria-hidden="true" tabindex="-1"></a><span class="in">    y = "Median price (DKK)",</span></span>
<span id="cb1-610"><a href="#cb1-610" aria-hidden="true" tabindex="-1"></a><span class="in">    color = "Segment"</span></span>
<span id="cb1-611"><a href="#cb1-611" aria-hidden="true" tabindex="-1"></a><span class="in">  ) +</span></span>
<span id="cb1-612"><a href="#cb1-612" aria-hidden="true" tabindex="-1"></a><span class="in">  scale_y_continuous(labels = scales::comma) +</span></span>
<span id="cb1-613"><a href="#cb1-613" aria-hidden="true" tabindex="-1"></a><span class="in">  theme_minimal(base_size = 13) +</span></span>
<span id="cb1-614"><a href="#cb1-614" aria-hidden="true" tabindex="-1"></a><span class="in">  theme(</span></span>
<span id="cb1-615"><a href="#cb1-615" aria-hidden="true" tabindex="-1"></a><span class="in">    plot.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-616"><a href="#cb1-616" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-617"><a href="#cb1-617" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.major = element_line(color = "#444444"),</span></span>
<span id="cb1-618"><a href="#cb1-618" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.minor = element_blank(),</span></span>
<span id="cb1-619"><a href="#cb1-619" aria-hidden="true" tabindex="-1"></a><span class="in">    text = element_text(color = "white"),</span></span>
<span id="cb1-620"><a href="#cb1-620" aria-hidden="true" tabindex="-1"></a><span class="in">    axis.text = element_text(color = "white"),</span></span>
<span id="cb1-621"><a href="#cb1-621" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-622"><a href="#cb1-622" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.key = element_rect(fill = "#1e1e1e")</span></span>
<span id="cb1-623"><a href="#cb1-623" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-624"><a href="#cb1-624" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-625"><a href="#cb1-625" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-626"><a href="#cb1-626" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-627"><a href="#cb1-627" aria-hidden="true" tabindex="-1"></a>**Interpretation**\</span>
<span id="cb1-628"><a href="#cb1-628" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-629"><a href="#cb1-629" aria-hidden="true" tabindex="-1"></a>This scatterplot shows the relationship between **weekly listing volume** (x-axis) and **median retail price** (y-axis) for three EV brands: **Tesla**, **VW ID**, and **Skoda Enyaq**. Each point represents one week; the trendlines show the direction and strength of that relationship for each brand. Two visual elements are key here:</span>
<span id="cb1-630"><a href="#cb1-630" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-631"><a href="#cb1-631" aria-hidden="true" tabindex="-1"></a>**Slope of the line** → how prices respond to changes in volume\</span>
<span id="cb1-632"><a href="#cb1-632" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-633"><a href="#cb1-633" aria-hidden="true" tabindex="-1"></a>– A **steeper negative slope** means prices drop as listings rise (more price-sensitive).\</span>
<span id="cb1-634"><a href="#cb1-634" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-635"><a href="#cb1-635" aria-hidden="true" tabindex="-1"></a>– A **flat line** indicates prices remain stable regardless of supply.</span>
<span id="cb1-636"><a href="#cb1-636" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-637"><a href="#cb1-637" aria-hidden="true" tabindex="-1"></a>**Length of the line** → the range of observed volumes\</span>
<span id="cb1-638"><a href="#cb1-638" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-639"><a href="#cb1-639" aria-hidden="true" tabindex="-1"></a>– A **longer line** means that the segment has been listed across a wider range of weekly volumes.\</span>
<span id="cb1-640"><a href="#cb1-640" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-641"><a href="#cb1-641" aria-hidden="true" tabindex="-1"></a>– A **shorter line** signals that the brand rarely reaches high volumes – so price behavior is only observed within a narrower supply band.</span>
<span id="cb1-642"><a href="#cb1-642" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-643"><a href="#cb1-643" aria-hidden="true" tabindex="-1"></a>**Findings**\</span>
<span id="cb1-644"><a href="#cb1-644" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-645"><a href="#cb1-645" aria-hidden="true" tabindex="-1"></a>– **VW ID** combines a long line and a steep slope – indicating both high listing activity and strong price sensitivity.\</span>
<span id="cb1-646"><a href="#cb1-646" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-647"><a href="#cb1-647" aria-hidden="true" tabindex="-1"></a>– **Skoda Enyaq** has a shorter but steep line – fewer weeks with high volume, but still a clear price drop pattern.\</span>
<span id="cb1-648"><a href="#cb1-648" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-649"><a href="#cb1-649" aria-hidden="true" tabindex="-1"></a>– **Tesla** displays a flat and relatively short line – suggesting stable prices across a narrow volume range, reinforcing earlier signs of centralized pricing or limited responsiveness to weekly market conditions.</span>
<span id="cb1-650"><a href="#cb1-650" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-651"><a href="#cb1-651" aria-hidden="true" tabindex="-1"></a>Together, these patterns reveal that **volume alone doesn't determine pricing power** – the brand matters, and Tesla continues to diverge from peers in how it responds to market shifts.</span>
<span id="cb1-652"><a href="#cb1-652" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-653"><a href="#cb1-653" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-654"><a href="#cb1-654" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-655"><a href="#cb1-655" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-656"><a href="#cb1-656" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-657"><a href="#cb1-657" aria-hidden="true" tabindex="-1"></a><span class="fu">## 📐 Smoothed Price Trends (LOESS)</span></span>
<span id="cb1-658"><a href="#cb1-658" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-659"><a href="#cb1-659" aria-hidden="true" tabindex="-1"></a><span class="in">```{r loess_price_trend, fig.width=9, fig.height=5, fig.cap="LOESS-smoothed price trends per segment"}</span></span>
<span id="cb1-660"><a href="#cb1-660" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(price_loess, aes(x = week, y = median_price, color = segment)) +</span></span>
<span id="cb1-661"><a href="#cb1-661" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_smooth(method = "loess", span = 0.3, se = FALSE, size = 1.2) +</span></span>
<span id="cb1-662"><a href="#cb1-662" aria-hidden="true" tabindex="-1"></a><span class="in">  labs(</span></span>
<span id="cb1-663"><a href="#cb1-663" aria-hidden="true" tabindex="-1"></a><span class="in">    title = "LOESS-smoothed median retail price",</span></span>
<span id="cb1-664"><a href="#cb1-664" aria-hidden="true" tabindex="-1"></a><span class="in">    subtitle = "Weekly prices by segment – Retail only",</span></span>
<span id="cb1-665"><a href="#cb1-665" aria-hidden="true" tabindex="-1"></a><span class="in">    x = "Week",</span></span>
<span id="cb1-666"><a href="#cb1-666" aria-hidden="true" tabindex="-1"></a><span class="in">    y = "DKK",</span></span>
<span id="cb1-667"><a href="#cb1-667" aria-hidden="true" tabindex="-1"></a><span class="in">    color = "Segment"</span></span>
<span id="cb1-668"><a href="#cb1-668" aria-hidden="true" tabindex="-1"></a><span class="in">  ) +</span></span>
<span id="cb1-669"><a href="#cb1-669" aria-hidden="true" tabindex="-1"></a><span class="in">  scale_color_manual(values = c(</span></span>
<span id="cb1-670"><a href="#cb1-670" aria-hidden="true" tabindex="-1"></a><span class="in">    "Tesla" = "#6BE7C2",</span></span>
<span id="cb1-671"><a href="#cb1-671" aria-hidden="true" tabindex="-1"></a><span class="in">    "VW ID" = "#8BC34A",</span></span>
<span id="cb1-672"><a href="#cb1-672" aria-hidden="true" tabindex="-1"></a><span class="in">    "Electric vehicles" = "#FFDD57",</span></span>
<span id="cb1-673"><a href="#cb1-673" aria-hidden="true" tabindex="-1"></a><span class="in">    "Fossil vehicles" = "#FF6B6B"</span></span>
<span id="cb1-674"><a href="#cb1-674" aria-hidden="true" tabindex="-1"></a><span class="in">  )) +</span></span>
<span id="cb1-675"><a href="#cb1-675" aria-hidden="true" tabindex="-1"></a><span class="in">  scale_y_continuous(labels = scales::comma) +</span></span>
<span id="cb1-676"><a href="#cb1-676" aria-hidden="true" tabindex="-1"></a><span class="in">  theme_minimal(base_size = 13) +</span></span>
<span id="cb1-677"><a href="#cb1-677" aria-hidden="true" tabindex="-1"></a><span class="in">  theme(</span></span>
<span id="cb1-678"><a href="#cb1-678" aria-hidden="true" tabindex="-1"></a><span class="in">    plot.background = element_rect(fill = "#1e1e1e", color = NA),</span></span>
<span id="cb1-679"><a href="#cb1-679" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.background = element_rect(fill = "#1e1e1e", color = NA),</span></span>
<span id="cb1-680"><a href="#cb1-680" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.major = element_line(color = "#444444"),</span></span>
<span id="cb1-681"><a href="#cb1-681" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.minor = element_blank(),</span></span>
<span id="cb1-682"><a href="#cb1-682" aria-hidden="true" tabindex="-1"></a><span class="in">    text = element_text(color = "white"),</span></span>
<span id="cb1-683"><a href="#cb1-683" aria-hidden="true" tabindex="-1"></a><span class="in">    axis.text = element_text(color = "white"),</span></span>
<span id="cb1-684"><a href="#cb1-684" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-685"><a href="#cb1-685" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.key = element_rect(fill = "#1e1e1e")</span></span>
<span id="cb1-686"><a href="#cb1-686" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-687"><a href="#cb1-687" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-688"><a href="#cb1-688" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-689"><a href="#cb1-689" aria-hidden="true" tabindex="-1"></a>**Interpretation**\</span>
<span id="cb1-690"><a href="#cb1-690" aria-hidden="true" tabindex="-1"></a>This chart shows smoothed weekly median prices using LOESS – a local regression technique that highlights broad trends while filtering out week-to-week noise.</span>
<span id="cb1-691"><a href="#cb1-691" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-692"><a href="#cb1-692" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Fossil vehicles** display a steady decline, suggesting sustained price pressure across the period.\</span>
<span id="cb1-693"><a href="#cb1-693" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Electric vehicles** show more fluctuation but a generally downward trend, indicating both volatility and emerging price normalization.\</span>
<span id="cb1-694"><a href="#cb1-694" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**VW ID** closely tracks the broader EV market, reinforcing its role as a representative subsegment.\</span>
<span id="cb1-695"><a href="#cb1-695" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Tesla** stands out with elevated and relatively stable prices – despite some variation, the curve suggests resilience compared to peers.</span>
<span id="cb1-696"><a href="#cb1-696" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-697"><a href="#cb1-697" aria-hidden="true" tabindex="-1"></a>In essence, this view highlights **the structural separation in pricing levels** between segments – with Tesla maintaining premium positioning.</span>
<span id="cb1-698"><a href="#cb1-698" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-699"><a href="#cb1-699" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-700"><a href="#cb1-700" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-701"><a href="#cb1-701" aria-hidden="true" tabindex="-1"></a><span class="fu">## 🧠 **Final takeaway**</span></span>
<span id="cb1-702"><a href="#cb1-702" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-703"><a href="#cb1-703" aria-hidden="true" tabindex="-1"></a>While most segments followed textbook supply–demand logic (volume up → price down), Tesla defied the trend. Its prices remained elevated and stable, even as listings grew – signaling brand-specific dynamics, insulation, or deliberate pricing control.</span>
<span id="cb1-704"><a href="#cb1-704" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-705"><a href="#cb1-705" aria-hidden="true" tabindex="-1"></a>Tesla doesn’t just behave differently – it moves on its own terms.</span>
<span id="cb1-706"><a href="#cb1-706" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-707"><a href="#cb1-707" aria-hidden="true" tabindex="-1"></a>**In short, the pattern is visible – and we’ve surfaced the shift.**</span>
<span id="cb1-708"><a href="#cb1-708" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-709"><a href="#cb1-709" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-710"><a href="#cb1-710" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-711"><a href="#cb1-711" aria-hidden="true" tabindex="-1"></a><span class="fu"># 📎 Appendix</span></span>
<span id="cb1-712"><a href="#cb1-712" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-713"><a href="#cb1-713" aria-hidden="true" tabindex="-1"></a><span class="fu">## Weekly median retail prices</span></span>
<span id="cb1-714"><a href="#cb1-714" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-715"><a href="#cb1-715" aria-hidden="true" tabindex="-1"></a><span class="in">```{r price_median_all, fig.width=9, fig.height=5, fig.cap="Weekly median retail prices – Total market, Fossil, and EV segments"}</span></span>
<span id="cb1-716"><a href="#cb1-716" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(price_trend, aes(x = week, y = median_price, color = segment)) +</span></span>
<span id="cb1-717"><a href="#cb1-717" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_line(size = 1.3) +</span></span>
<span id="cb1-718"><a href="#cb1-718" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_vline(data = events, aes(xintercept = date), linetype = "dashed", color = "white") +</span></span>
<span id="cb1-719"><a href="#cb1-719" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_text(data = events, aes(x = date, y = Inf, label = label),</span></span>
<span id="cb1-720"><a href="#cb1-720" aria-hidden="true" tabindex="-1"></a><span class="in">            angle = 90, vjust = -0.5, hjust = 1.1,</span></span>
<span id="cb1-721"><a href="#cb1-721" aria-hidden="true" tabindex="-1"></a><span class="in">            size = 3.5, color = "white", inherit.aes = FALSE) +</span></span>
<span id="cb1-722"><a href="#cb1-722" aria-hidden="true" tabindex="-1"></a><span class="in">  scale_y_continuous(labels = scales::comma) +</span></span>
<span id="cb1-723"><a href="#cb1-723" aria-hidden="true" tabindex="-1"></a><span class="in">  scale_color_manual(values = c(</span></span>
<span id="cb1-724"><a href="#cb1-724" aria-hidden="true" tabindex="-1"></a><span class="in">    "Total market" = "#00c0c7",</span></span>
<span id="cb1-725"><a href="#cb1-725" aria-hidden="true" tabindex="-1"></a><span class="in">    "Electric vehicles" = "#FFDD57",</span></span>
<span id="cb1-726"><a href="#cb1-726" aria-hidden="true" tabindex="-1"></a><span class="in">    "Fossil vehicles" = "#FF6B6B"</span></span>
<span id="cb1-727"><a href="#cb1-727" aria-hidden="true" tabindex="-1"></a><span class="in">  )) +</span></span>
<span id="cb1-728"><a href="#cb1-728" aria-hidden="true" tabindex="-1"></a><span class="in">  labs(</span></span>
<span id="cb1-729"><a href="#cb1-729" aria-hidden="true" tabindex="-1"></a><span class="in">    title = "Weekly median retail prices",</span></span>
<span id="cb1-730"><a href="#cb1-730" aria-hidden="true" tabindex="-1"></a><span class="in">    subtitle = "Total vs Electric vs Fossil (Retail only)",</span></span>
<span id="cb1-731"><a href="#cb1-731" aria-hidden="true" tabindex="-1"></a><span class="in">    x = "Week",</span></span>
<span id="cb1-732"><a href="#cb1-732" aria-hidden="true" tabindex="-1"></a><span class="in">    y = "DKK",</span></span>
<span id="cb1-733"><a href="#cb1-733" aria-hidden="true" tabindex="-1"></a><span class="in">    color = "Segment"</span></span>
<span id="cb1-734"><a href="#cb1-734" aria-hidden="true" tabindex="-1"></a><span class="in">  ) +</span></span>
<span id="cb1-735"><a href="#cb1-735" aria-hidden="true" tabindex="-1"></a><span class="in">  theme_minimal(base_size = 13) +</span></span>
<span id="cb1-736"><a href="#cb1-736" aria-hidden="true" tabindex="-1"></a><span class="in">  theme(</span></span>
<span id="cb1-737"><a href="#cb1-737" aria-hidden="true" tabindex="-1"></a><span class="in">    plot.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-738"><a href="#cb1-738" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-739"><a href="#cb1-739" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.major = element_line(color = "#444444"),</span></span>
<span id="cb1-740"><a href="#cb1-740" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.minor = element_blank(),</span></span>
<span id="cb1-741"><a href="#cb1-741" aria-hidden="true" tabindex="-1"></a><span class="in">    text = element_text(color = "white"),</span></span>
<span id="cb1-742"><a href="#cb1-742" aria-hidden="true" tabindex="-1"></a><span class="in">    axis.text = element_text(color = "white"),</span></span>
<span id="cb1-743"><a href="#cb1-743" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-744"><a href="#cb1-744" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.key = element_rect(fill = "#1e1e1e")</span></span>
<span id="cb1-745"><a href="#cb1-745" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-746"><a href="#cb1-746" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-747"><a href="#cb1-747" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-748"><a href="#cb1-748" aria-hidden="true" tabindex="-1"></a>Fossil vehicles held stable throughout the period, with only gradual decline – a hallmark of a mature, supply-stable segment. EV prices, by contrast, started high and trended downward. This supports the idea of market normalization: more listings, more competition, and an erosion of the early EV price premium.</span>
<span id="cb1-749"><a href="#cb1-749" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-750"><a href="#cb1-750" aria-hidden="true" tabindex="-1"></a><span class="fu">## Weekly median retail prices - Tesla vs VW ID</span></span>
<span id="cb1-751"><a href="#cb1-751" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-752"><a href="#cb1-752" aria-hidden="true" tabindex="-1"></a><span class="in">```{r price_median_tesla_vw, fig.width=9, fig.height=5, fig.cap="Weekly median prices – Tesla vs VW ID"}</span></span>
<span id="cb1-753"><a href="#cb1-753" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(price_focus_weekly, aes(x = week, y = median_price, color = segment)) +</span></span>
<span id="cb1-754"><a href="#cb1-754" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_line(size = 1.3) +</span></span>
<span id="cb1-755"><a href="#cb1-755" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_vline(data = events, aes(xintercept = date), linetype = "dashed", color = "white") +</span></span>
<span id="cb1-756"><a href="#cb1-756" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_text(data = events, aes(x = date, y = Inf, label = label),</span></span>
<span id="cb1-757"><a href="#cb1-757" aria-hidden="true" tabindex="-1"></a><span class="in">            angle = 90, vjust = -0.5, hjust = 1.1,</span></span>
<span id="cb1-758"><a href="#cb1-758" aria-hidden="true" tabindex="-1"></a><span class="in">            size = 3.5, color = "white", inherit.aes = FALSE) +</span></span>
<span id="cb1-759"><a href="#cb1-759" aria-hidden="true" tabindex="-1"></a><span class="in">  scale_y_continuous(labels = scales::comma) +</span></span>
<span id="cb1-760"><a href="#cb1-760" aria-hidden="true" tabindex="-1"></a><span class="in">  scale_color_manual(values = c(</span></span>
<span id="cb1-761"><a href="#cb1-761" aria-hidden="true" tabindex="-1"></a><span class="in">    "Tesla" = "#6BE7C2",</span></span>
<span id="cb1-762"><a href="#cb1-762" aria-hidden="true" tabindex="-1"></a><span class="in">    "VW ID" = "#8BC34A"</span></span>
<span id="cb1-763"><a href="#cb1-763" aria-hidden="true" tabindex="-1"></a><span class="in">  )) +</span></span>
<span id="cb1-764"><a href="#cb1-764" aria-hidden="true" tabindex="-1"></a><span class="in">  labs(</span></span>
<span id="cb1-765"><a href="#cb1-765" aria-hidden="true" tabindex="-1"></a><span class="in">    title = "Weekly median prices – Tesla vs VW ID",</span></span>
<span id="cb1-766"><a href="#cb1-766" aria-hidden="true" tabindex="-1"></a><span class="in">    subtitle = "Retail listings only (Apr 2024 – Mar 2025)",</span></span>
<span id="cb1-767"><a href="#cb1-767" aria-hidden="true" tabindex="-1"></a><span class="in">    x = "Week",</span></span>
<span id="cb1-768"><a href="#cb1-768" aria-hidden="true" tabindex="-1"></a><span class="in">    y = "DKK",</span></span>
<span id="cb1-769"><a href="#cb1-769" aria-hidden="true" tabindex="-1"></a><span class="in">    color = "Brand"</span></span>
<span id="cb1-770"><a href="#cb1-770" aria-hidden="true" tabindex="-1"></a><span class="in">  ) +</span></span>
<span id="cb1-771"><a href="#cb1-771" aria-hidden="true" tabindex="-1"></a><span class="in">  theme_minimal(base_size = 13) +</span></span>
<span id="cb1-772"><a href="#cb1-772" aria-hidden="true" tabindex="-1"></a><span class="in">  theme(</span></span>
<span id="cb1-773"><a href="#cb1-773" aria-hidden="true" tabindex="-1"></a><span class="in">    plot.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-774"><a href="#cb1-774" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-775"><a href="#cb1-775" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.major = element_line(color = "#444444"),</span></span>
<span id="cb1-776"><a href="#cb1-776" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.minor = element_blank(),</span></span>
<span id="cb1-777"><a href="#cb1-777" aria-hidden="true" tabindex="-1"></a><span class="in">    text = element_text(color = "white"),</span></span>
<span id="cb1-778"><a href="#cb1-778" aria-hidden="true" tabindex="-1"></a><span class="in">    axis.text = element_text(color = "white"),</span></span>
<span id="cb1-779"><a href="#cb1-779" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-780"><a href="#cb1-780" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.key = element_rect(fill = "#1e1e1e")</span></span>
<span id="cb1-781"><a href="#cb1-781" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-782"><a href="#cb1-782" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-783"><a href="#cb1-783" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-784"><a href="#cb1-784" aria-hidden="true" tabindex="-1"></a>Despite similar volumes, price dynamics diverge sharply. VW ID follows a modest and stable path. Tesla, meanwhile, swings unpredictably – suggesting sensitivity to external cues or internal recalibration. Volatility here may not signal chaos, but control: pricing used as an active lever.</span>
<span id="cb1-785"><a href="#cb1-785" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-786"><a href="#cb1-786" aria-hidden="true" tabindex="-1"></a><span class="fu">## 📏 Indexed Prices (Week 1 = 100)</span></span>
<span id="cb1-787"><a href="#cb1-787" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-788"><a href="#cb1-788" aria-hidden="true" tabindex="-1"></a><span class="in">```{r price_index_plot, fig.width=9, fig.height=5, fig.cap="Retail price index per segment (Week 1 = 100)"}</span></span>
<span id="cb1-789"><a href="#cb1-789" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(price_index, aes(x = week, y = price_index, color = segment)) +</span></span>
<span id="cb1-790"><a href="#cb1-790" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_line(size = 1.2) +</span></span>
<span id="cb1-791"><a href="#cb1-791" aria-hidden="true" tabindex="-1"></a><span class="in">  labs(</span></span>
<span id="cb1-792"><a href="#cb1-792" aria-hidden="true" tabindex="-1"></a><span class="in">    title = "Retail price index (Week 1 = 100)",</span></span>
<span id="cb1-793"><a href="#cb1-793" aria-hidden="true" tabindex="-1"></a><span class="in">    subtitle = "Weekly median prices, indexed to April 2024",</span></span>
<span id="cb1-794"><a href="#cb1-794" aria-hidden="true" tabindex="-1"></a><span class="in">    x = "Week",</span></span>
<span id="cb1-795"><a href="#cb1-795" aria-hidden="true" tabindex="-1"></a><span class="in">    y = "Price index",</span></span>
<span id="cb1-796"><a href="#cb1-796" aria-hidden="true" tabindex="-1"></a><span class="in">    color = "Segment"</span></span>
<span id="cb1-797"><a href="#cb1-797" aria-hidden="true" tabindex="-1"></a><span class="in">  ) +</span></span>
<span id="cb1-798"><a href="#cb1-798" aria-hidden="true" tabindex="-1"></a><span class="in">  scale_color_manual(values = c(</span></span>
<span id="cb1-799"><a href="#cb1-799" aria-hidden="true" tabindex="-1"></a><span class="in">    "Tesla" = "#6BE7C2",</span></span>
<span id="cb1-800"><a href="#cb1-800" aria-hidden="true" tabindex="-1"></a><span class="in">    "VW ID" = "#8BC34A",</span></span>
<span id="cb1-801"><a href="#cb1-801" aria-hidden="true" tabindex="-1"></a><span class="in">    "Electric vehicles" = "#FFDD57",</span></span>
<span id="cb1-802"><a href="#cb1-802" aria-hidden="true" tabindex="-1"></a><span class="in">    "Fossil vehicles" = "#FF6B6B"</span></span>
<span id="cb1-803"><a href="#cb1-803" aria-hidden="true" tabindex="-1"></a><span class="in">  )) +</span></span>
<span id="cb1-804"><a href="#cb1-804" aria-hidden="true" tabindex="-1"></a><span class="in">  theme_minimal(base_size = 13) +</span></span>
<span id="cb1-805"><a href="#cb1-805" aria-hidden="true" tabindex="-1"></a><span class="in">  theme(</span></span>
<span id="cb1-806"><a href="#cb1-806" aria-hidden="true" tabindex="-1"></a><span class="in">    plot.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-807"><a href="#cb1-807" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-808"><a href="#cb1-808" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.major = element_line(color = "#444444"),</span></span>
<span id="cb1-809"><a href="#cb1-809" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.minor = element_blank(),</span></span>
<span id="cb1-810"><a href="#cb1-810" aria-hidden="true" tabindex="-1"></a><span class="in">    text = element_text(color = "white"),</span></span>
<span id="cb1-811"><a href="#cb1-811" aria-hidden="true" tabindex="-1"></a><span class="in">    axis.text = element_text(color = "white"),</span></span>
<span id="cb1-812"><a href="#cb1-812" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-813"><a href="#cb1-813" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.key = element_rect(fill = "#1e1e1e")</span></span>
<span id="cb1-814"><a href="#cb1-814" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-815"><a href="#cb1-815" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-816"><a href="#cb1-816" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-817"><a href="#cb1-817" aria-hidden="true" tabindex="-1"></a>Indexing reveals a clearer narrative: Fossil and EV prices decline together, but Tesla defies the trend. Its price index remains elevated – fluctuating, but consistently above peers. This reinforces earlier points: Tesla isn't just another EV brand, it moves to its own logic – structurally distinct in both volume and price.</span>
<span id="cb1-818"><a href="#cb1-818" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-819"><a href="#cb1-819" aria-hidden="true" tabindex="-1"></a><span class="fu">## Total markets volume vs. Price – Scatter</span></span>
<span id="cb1-820"><a href="#cb1-820" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-821"><a href="#cb1-821" aria-hidden="true" tabindex="-1"></a><span class="in">```{r price_volume_scatter, fig.width=9, fig.height=5, fig.cap="Scatterplot – Weekly volume vs median price (per segment)"}</span></span>
<span id="cb1-822"><a href="#cb1-822" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(vol_vs_price, aes(x = n, y = median_price, color = segment)) +</span></span>
<span id="cb1-823"><a href="#cb1-823" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_point(alpha = 0.7) +</span></span>
<span id="cb1-824"><a href="#cb1-824" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_smooth(method = "lm", se = FALSE, size = 1.2) +</span></span>
<span id="cb1-825"><a href="#cb1-825" aria-hidden="true" tabindex="-1"></a><span class="in">  labs(</span></span>
<span id="cb1-826"><a href="#cb1-826" aria-hidden="true" tabindex="-1"></a><span class="in">    title = "Volume vs. median retail price",</span></span>
<span id="cb1-827"><a href="#cb1-827" aria-hidden="true" tabindex="-1"></a><span class="in">    subtitle = "Each point is one week (Retail only)",</span></span>
<span id="cb1-828"><a href="#cb1-828" aria-hidden="true" tabindex="-1"></a><span class="in">    x = "Number of listings (weekly)",</span></span>
<span id="cb1-829"><a href="#cb1-829" aria-hidden="true" tabindex="-1"></a><span class="in">    y = "Median price (DKK)",</span></span>
<span id="cb1-830"><a href="#cb1-830" aria-hidden="true" tabindex="-1"></a><span class="in">    color = "Segment"</span></span>
<span id="cb1-831"><a href="#cb1-831" aria-hidden="true" tabindex="-1"></a><span class="in">  ) +</span></span>
<span id="cb1-832"><a href="#cb1-832" aria-hidden="true" tabindex="-1"></a><span class="in">  scale_color_manual(values = c(</span></span>
<span id="cb1-833"><a href="#cb1-833" aria-hidden="true" tabindex="-1"></a><span class="in">    "Tesla" = "#6BE7C2",</span></span>
<span id="cb1-834"><a href="#cb1-834" aria-hidden="true" tabindex="-1"></a><span class="in">    "VW ID" = "#8BC34A",</span></span>
<span id="cb1-835"><a href="#cb1-835" aria-hidden="true" tabindex="-1"></a><span class="in">    "Electric vehicles" = "#FFDD57",</span></span>
<span id="cb1-836"><a href="#cb1-836" aria-hidden="true" tabindex="-1"></a><span class="in">    "Fossil vehicles" = "#FF6B6B"</span></span>
<span id="cb1-837"><a href="#cb1-837" aria-hidden="true" tabindex="-1"></a><span class="in">  )) +</span></span>
<span id="cb1-838"><a href="#cb1-838" aria-hidden="true" tabindex="-1"></a><span class="in">  scale_y_continuous(labels = scales::comma) +</span></span>
<span id="cb1-839"><a href="#cb1-839" aria-hidden="true" tabindex="-1"></a><span class="in">  theme_minimal(base_size = 13) +</span></span>
<span id="cb1-840"><a href="#cb1-840" aria-hidden="true" tabindex="-1"></a><span class="in">  theme(</span></span>
<span id="cb1-841"><a href="#cb1-841" aria-hidden="true" tabindex="-1"></a><span class="in">    plot.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-842"><a href="#cb1-842" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-843"><a href="#cb1-843" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.major = element_line(color = "#444444"),</span></span>
<span id="cb1-844"><a href="#cb1-844" aria-hidden="true" tabindex="-1"></a><span class="in">    panel.grid.minor = element_blank(),</span></span>
<span id="cb1-845"><a href="#cb1-845" aria-hidden="true" tabindex="-1"></a><span class="in">    text = element_text(color = "white"),</span></span>
<span id="cb1-846"><a href="#cb1-846" aria-hidden="true" tabindex="-1"></a><span class="in">    axis.text = element_text(color = "white"),</span></span>
<span id="cb1-847"><a href="#cb1-847" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.background = element_rect(fill = "#1e1e1e"),</span></span>
<span id="cb1-848"><a href="#cb1-848" aria-hidden="true" tabindex="-1"></a><span class="in">    legend.key = element_rect(fill = "#1e1e1e")</span></span>
<span id="cb1-849"><a href="#cb1-849" aria-hidden="true" tabindex="-1"></a><span class="in">  )</span></span>
<span id="cb1-850"><a href="#cb1-850" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-851"><a href="#cb1-851" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-852"><a href="#cb1-852" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-853"><a href="#cb1-853" aria-hidden="true" tabindex="-1"></a>This scatterplot quantifies what we’ve hinted at: volume correlates negatively with price across segments – except for Tesla. Where others follow the textbook rule (more listings = lower prices), Tesla’s line is nearly flat. It absorbs volume without discounting – or at least, without obvious market-based pressure.</span>
<span id="cb1-854"><a href="#cb1-854" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-855"><a href="#cb1-855" aria-hidden="true" tabindex="-1"></a>Together, these charts reinforce the central pattern: Tesla doesn’t just behave differently – it prices differently, moves differently, and responds to change on its own terms. For market watchers, that makes it both harder to predict – and more important to watch.</span>
<span id="cb1-856"><a href="#cb1-856" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-857"><a href="#cb1-857" aria-hidden="true" tabindex="-1"></a>\</span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>